// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ApiKey struct {
	pulumi.CustomResourceState

	// Grant all current and future permissions. Requires caller authority. Defaults to false.
	AllFuturePermissions pulumi.BoolOutput `pulumi:"allFuturePermissions"`
	// API ID used to authenticate with this key.
	ApiId pulumi.StringOutput `pulumi:"apiId"`
	// Secret returned only at creation. Preserved during refresh and updates; unavailable after import.
	ApiKey pulumi.StringOutput `pulumi:"apiKey"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Disable authentication with the key. Defaults to false.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Actual display name returned by the API, including a generated name when name is omitted.
	EffectiveName pulumi.StringOutput `pulumi:"effectiveName"`
	// Current grants returned by the API, including expansion of all_future_permissions.
	EffectivePermissions pulumi.StringArrayOutput `pulumi:"effectivePermissions"`
	// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
	// Last update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewApiKey registers a new resource with the given unique name, arguments, and options.
func NewApiKey(ctx *pulumi.Context,
	name string, args *ApiKeyArgs, opts ...pulumi.ResourceOption) (*ApiKey, error) {
	if args == nil {
		args = &ApiKeyArgs{}
	}

	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApiKey
	err := ctx.RegisterResource("html-css-to-image:index:ApiKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApiKey gets an existing ApiKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApiKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApiKeyState, opts ...pulumi.ResourceOption) (*ApiKey, error) {
	var resource ApiKey
	err := ctx.ReadResource("html-css-to-image:index:ApiKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApiKey resources.
type apiKeyState struct {
	// Grant all current and future permissions. Requires caller authority. Defaults to false.
	AllFuturePermissions *bool `pulumi:"allFuturePermissions"`
	// API ID used to authenticate with this key.
	ApiId *string `pulumi:"apiId"`
	// Secret returned only at creation. Preserved during refresh and updates; unavailable after import.
	ApiKey *string `pulumi:"apiKey"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
	Description *string `pulumi:"description"`
	// Disable authentication with the key. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Actual display name returned by the API, including a generated name when name is omitted.
	EffectiveName *string `pulumi:"effectiveName"`
	// Current grants returned by the API, including expansion of all_future_permissions.
	EffectivePermissions []string `pulumi:"effectivePermissions"`
	// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
	Name *string `pulumi:"name"`
	// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
	Permissions []string `pulumi:"permissions"`
	// Last update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ApiKeyState struct {
	// Grant all current and future permissions. Requires caller authority. Defaults to false.
	AllFuturePermissions pulumi.BoolPtrInput
	// API ID used to authenticate with this key.
	ApiId pulumi.StringPtrInput
	// Secret returned only at creation. Preserved during refresh and updates; unavailable after import.
	ApiKey pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
	Description pulumi.StringPtrInput
	// Disable authentication with the key. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Actual display name returned by the API, including a generated name when name is omitted.
	EffectiveName pulumi.StringPtrInput
	// Current grants returned by the API, including expansion of all_future_permissions.
	EffectivePermissions pulumi.StringArrayInput
	// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
	Name pulumi.StringPtrInput
	// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
	Permissions pulumi.StringArrayInput
	// Last update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (ApiKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*apiKeyState)(nil)).Elem()
}

type apiKeyArgs struct {
	// Grant all current and future permissions. Requires caller authority. Defaults to false.
	AllFuturePermissions *bool `pulumi:"allFuturePermissions"`
	// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
	Description *string `pulumi:"description"`
	// Disable authentication with the key. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
	Name *string `pulumi:"name"`
	// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
	Permissions []string `pulumi:"permissions"`
}

// The set of arguments for constructing a ApiKey resource.
type ApiKeyArgs struct {
	// Grant all current and future permissions. Requires caller authority. Defaults to false.
	AllFuturePermissions pulumi.BoolPtrInput
	// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
	Description pulumi.StringPtrInput
	// Disable authentication with the key. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
	Name pulumi.StringPtrInput
	// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
	Permissions pulumi.StringArrayInput
}

func (ApiKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apiKeyArgs)(nil)).Elem()
}

type ApiKeyInput interface {
	pulumi.Input

	ToApiKeyOutput() ApiKeyOutput
	ToApiKeyOutputWithContext(ctx context.Context) ApiKeyOutput
}

func (*ApiKey) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiKey)(nil)).Elem()
}

func (i *ApiKey) ToApiKeyOutput() ApiKeyOutput {
	return i.ToApiKeyOutputWithContext(context.Background())
}

func (i *ApiKey) ToApiKeyOutputWithContext(ctx context.Context) ApiKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiKeyOutput)
}

type ApiKeyOutput struct{ *pulumi.OutputState }

func (ApiKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiKey)(nil)).Elem()
}

func (o ApiKeyOutput) ToApiKeyOutput() ApiKeyOutput {
	return o
}

func (o ApiKeyOutput) ToApiKeyOutputWithContext(ctx context.Context) ApiKeyOutput {
	return o
}

// Grant all current and future permissions. Requires caller authority. Defaults to false.
func (o ApiKeyOutput) AllFuturePermissions() pulumi.BoolOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.BoolOutput { return v.AllFuturePermissions }).(pulumi.BoolOutput)
}

// API ID used to authenticate with this key.
func (o ApiKeyOutput) ApiId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringOutput { return v.ApiId }).(pulumi.StringOutput)
}

// Secret returned only at creation. Preserved during refresh and updates; unavailable after import.
func (o ApiKeyOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringOutput { return v.ApiKey }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o ApiKeyOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Purpose of the key, up to 2000 characters. Omitted, null, or blank clears it.
func (o ApiKeyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Disable authentication with the key. Defaults to false.
func (o ApiKeyOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Actual display name returned by the API, including a generated name when name is omitted.
func (o ApiKeyOutput) EffectiveName() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringOutput { return v.EffectiveName }).(pulumi.StringOutput)
}

// Current grants returned by the API, including expansion of all_future_permissions.
func (o ApiKeyOutput) EffectivePermissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringArrayOutput { return v.EffectivePermissions }).(pulumi.StringArrayOutput)
}

// Display name, up to 255 characters. Omitted, null, or blank uses an API-generated name based on the original creation time.
func (o ApiKeyOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Complete permission set. Required when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is false; [] grants no permissions. Must be omitted or empty when<span pulumi-lang-nodejs=" allFuturePermissions " pulumi-lang-dotnet=" AllFuturePermissions " pulumi-lang-go=" allFuturePermissions " pulumi-lang-python=" all_future_permissions " pulumi-lang-yaml=" allFuturePermissions " pulumi-lang-java=" allFuturePermissions " pulumi-lang-hcl=" all_future_permissions "> allFuturePermissions </span>is true.
func (o ApiKeyOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringArrayOutput { return v.Permissions }).(pulumi.StringArrayOutput)
}

// Last update timestamp.
func (o ApiKeyOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiKey) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApiKeyInput)(nil)).Elem(), &ApiKey{})
	pulumi.RegisterOutputType(ApiKeyOutput{})
}
