// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read the organization's external ID and HCTI writer role ARN before creating an AWS storage destination. No destination ID or input attributes are needed. This does not create a destination or test a bucket connection.
//
// The caller requires `storage_destinations:create_update` for this lookup.
//
// Use <span pulumi-lang-nodejs="`externalId`" pulumi-lang-dotnet="`ExternalId`" pulumi-lang-go="`externalId`" pulumi-lang-python="`external_id`" pulumi-lang-yaml="`externalId`" pulumi-lang-java="`externalId`" pulumi-lang-hcl="`external_id`">`externalId`</span> in the IAM role trust policy's `sts:ExternalId` condition, and <span pulumi-lang-nodejs="`writerRoleArn`" pulumi-lang-dotnet="`WriterRoleArn`" pulumi-lang-go="`writerRoleArn`" pulumi-lang-python="`writer_role_arn`" pulumi-lang-yaml="`writerRoleArn`" pulumi-lang-java="`writerRoleArn`" pulumi-lang-hcl="`writer_role_arn`">`writerRoleArn`</span> as its `Principal.AWS`, allowing `sts:AssumeRole`. An external-ID condition alone is not a complete trust policy. Reference the resulting role ARN from the storage destination so Terraform creates the role before HCTI tests the connection.
//
// | Output | Meaning |
// | --- | --- |
// | <span pulumi-lang-nodejs="`externalId`" pulumi-lang-dotnet="`ExternalId`" pulumi-lang-go="`externalId`" pulumi-lang-python="`external_id`" pulumi-lang-yaml="`externalId`" pulumi-lang-java="`externalId`" pulumi-lang-hcl="`external_id`">`externalId`</span> | Organization-specific external ID for the AWS role trust policy. |
// | <span pulumi-lang-nodejs="`writerRoleArn`" pulumi-lang-dotnet="`WriterRoleArn`" pulumi-lang-go="`writerRoleArn`" pulumi-lang-python="`writer_role_arn`" pulumi-lang-yaml="`writerRoleArn`" pulumi-lang-java="`writerRoleArn`" pulumi-lang-hcl="`writer_role_arn`">`writerRoleArn`</span> | HCTI writer role ARN to use as the trust policy's AWS principal. |
//
// Lookup failures remain errors, including authorization failures and HTTP 404.
//
// The returned <span pulumi-lang-nodejs="`writerRoleArn`" pulumi-lang-dotnet="`WriterRoleArn`" pulumi-lang-go="`writerRoleArn`" pulumi-lang-python="`writer_role_arn`" pulumi-lang-yaml="`writerRoleArn`" pulumi-lang-java="`writerRoleArn`" pulumi-lang-hcl="`writer_role_arn`">`writerRoleArn`</span> identifies HCTI's caller role. The storage destination's <span pulumi-lang-nodejs="`roleArn`" pulumi-lang-dotnet="`RoleArn`" pulumi-lang-go="`roleArn`" pulumi-lang-python="`role_arn`" pulumi-lang-yaml="`roleArn`" pulumi-lang-java="`roleArn`" pulumi-lang-hcl="`role_arn`">`roleArn`</span> identifies the role you create in your own AWS account.
func GetAwsStorageExternalId(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetAwsStorageExternalIdResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAwsStorageExternalIdResult
	err := ctx.Invoke("html-css-to-image:index:getAwsStorageExternalId", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getAwsStorageExternalId.
type GetAwsStorageExternalIdResult struct {
	ExternalId    string `pulumi:"externalId"`
	WriterRoleArn string `pulumi:"writerRoleArn"`
}

func GetAwsStorageExternalIdOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetAwsStorageExternalIdResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetAwsStorageExternalIdResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("html-css-to-image:index:getAwsStorageExternalId", nil, GetAwsStorageExternalIdResultOutput{}, options).(GetAwsStorageExternalIdResultOutput), nil
	}).(GetAwsStorageExternalIdResultOutput)
}

// A collection of values returned by getAwsStorageExternalId.
type GetAwsStorageExternalIdResultOutput struct{ *pulumi.OutputState }

func (GetAwsStorageExternalIdResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAwsStorageExternalIdResult)(nil)).Elem()
}

func (o GetAwsStorageExternalIdResultOutput) ToGetAwsStorageExternalIdResultOutput() GetAwsStorageExternalIdResultOutput {
	return o
}

func (o GetAwsStorageExternalIdResultOutput) ToGetAwsStorageExternalIdResultOutputWithContext(ctx context.Context) GetAwsStorageExternalIdResultOutput {
	return o
}

func (o GetAwsStorageExternalIdResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAwsStorageExternalIdResult) string { return v.ExternalId }).(pulumi.StringOutput)
}

func (o GetAwsStorageExternalIdResultOutput) WriterRoleArn() pulumi.StringOutput {
	return o.ApplyT(func(v GetAwsStorageExternalIdResult) string { return v.WriterRoleArn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAwsStorageExternalIdResultOutput{})
}
