// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read an existing HTML/CSS template without managing its lifecycle. Requires `templates:read`.
//
// ## Example Usage
//
// Omitting <span pulumi-lang-nodejs="`version`" pulumi-lang-dotnet="`Version`" pulumi-lang-go="`version`" pulumi-lang-python="`version`" pulumi-lang-yaml="`version`" pulumi-lang-java="`version`" pulumi-lang-hcl="`version`">`version`</span> resolves the latest version on every refresh. In this example a new template version changes the image's <span pulumi-lang-nodejs="`templateVersion`" pulumi-lang-dotnet="`TemplateVersion`" pulumi-lang-go="`templateVersion`" pulumi-lang-python="`template_version`" pulumi-lang-yaml="`templateVersion`" pulumi-lang-java="`templateVersion`" pulumi-lang-hcl="`template_version`">`templateVersion`</span>, so Terraform replaces the image. To pin the lookup, set <span pulumi-lang-nodejs="`version`" pulumi-lang-dotnet="`Version`" pulumi-lang-go="`version`" pulumi-lang-python="`version`" pulumi-lang-yaml="`version`" pulumi-lang-java="`version`" pulumi-lang-hcl="`version`">`version`</span> to a specific version identifier.
func LookupTemplate(ctx *pulumi.Context, args *LookupTemplateArgs, opts ...pulumi.InvokeOption) (*LookupTemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTemplateResult
	err := ctx.Invoke("html-css-to-image:index:getTemplate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTemplate.
type LookupTemplateArgs struct {
	Id      string  `pulumi:"id"`
	Version *string `pulumi:"version"`
}

// A collection of values returned by getTemplate.
type LookupTemplateResult struct {
	ColorScheme           string   `pulumi:"colorScheme"`
	CreatedAt             string   `pulumi:"createdAt"`
	Css                   string   `pulumi:"css"`
	Description           string   `pulumi:"description"`
	DeviceScale           float64  `pulumi:"deviceScale"`
	DisableTwemoji        bool     `pulumi:"disableTwemoji"`
	GoogleFonts           []string `pulumi:"googleFonts"`
	Html                  string   `pulumi:"html"`
	Id                    string   `pulumi:"id"`
	JumboMaxHeight        int      `pulumi:"jumboMaxHeight"`
	JumboMaxWidth         int      `pulumi:"jumboMaxWidth"`
	MaxWaitMs             int      `pulumi:"maxWaitMs"`
	MediaType             string   `pulumi:"mediaType"`
	MsDelay               int      `pulumi:"msDelay"`
	Name                  string   `pulumi:"name"`
	ProxyId               string   `pulumi:"proxyId"`
	RenderWhenReady       bool     `pulumi:"renderWhenReady"`
	Selector              string   `pulumi:"selector"`
	StorageDestinationId  string   `pulumi:"storageDestinationId"`
	TemplateType          string   `pulumi:"templateType"`
	Timezone              string   `pulumi:"timezone"`
	TransparentBackground bool     `pulumi:"transparentBackground"`
	UpdatedAt             string   `pulumi:"updatedAt"`
	Version               string   `pulumi:"version"`
	ViewportHeight        int      `pulumi:"viewportHeight"`
	ViewportLandscape     bool     `pulumi:"viewportLandscape"`
	ViewportMobile        bool     `pulumi:"viewportMobile"`
	ViewportTouch         bool     `pulumi:"viewportTouch"`
	ViewportWidth         int      `pulumi:"viewportWidth"`
}

func LookupTemplateOutput(ctx *pulumi.Context, args LookupTemplateOutputArgs, opts ...pulumi.InvokeOption) LookupTemplateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTemplateResultOutput, error) {
			args := v.(LookupTemplateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("html-css-to-image:index:getTemplate", args, LookupTemplateResultOutput{}, options).(LookupTemplateResultOutput), nil
		}).(LookupTemplateResultOutput)
}

// A collection of arguments for invoking getTemplate.
type LookupTemplateOutputArgs struct {
	Id      pulumi.StringInput    `pulumi:"id"`
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (LookupTemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTemplateArgs)(nil)).Elem()
}

// A collection of values returned by getTemplate.
type LookupTemplateResultOutput struct{ *pulumi.OutputState }

func (LookupTemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTemplateResult)(nil)).Elem()
}

func (o LookupTemplateResultOutput) ToLookupTemplateResultOutput() LookupTemplateResultOutput {
	return o
}

func (o LookupTemplateResultOutput) ToLookupTemplateResultOutputWithContext(ctx context.Context) LookupTemplateResultOutput {
	return o
}

func (o LookupTemplateResultOutput) ColorScheme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.ColorScheme }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) Css() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Css }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) DeviceScale() pulumi.Float64Output {
	return o.ApplyT(func(v LookupTemplateResult) float64 { return v.DeviceScale }).(pulumi.Float64Output)
}

func (o LookupTemplateResultOutput) DisableTwemoji() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.DisableTwemoji }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) GoogleFonts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupTemplateResult) []string { return v.GoogleFonts }).(pulumi.StringArrayOutput)
}

func (o LookupTemplateResultOutput) Html() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Html }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) JumboMaxHeight() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.JumboMaxHeight }).(pulumi.IntOutput)
}

func (o LookupTemplateResultOutput) JumboMaxWidth() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.JumboMaxWidth }).(pulumi.IntOutput)
}

func (o LookupTemplateResultOutput) MaxWaitMs() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.MaxWaitMs }).(pulumi.IntOutput)
}

func (o LookupTemplateResultOutput) MediaType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.MediaType }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) MsDelay() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.MsDelay }).(pulumi.IntOutput)
}

func (o LookupTemplateResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) ProxyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.ProxyId }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) RenderWhenReady() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.RenderWhenReady }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) Selector() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Selector }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) StorageDestinationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.StorageDestinationId }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) TemplateType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.TemplateType }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) Timezone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Timezone }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) TransparentBackground() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.TransparentBackground }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTemplateResult) string { return v.Version }).(pulumi.StringOutput)
}

func (o LookupTemplateResultOutput) ViewportHeight() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.ViewportHeight }).(pulumi.IntOutput)
}

func (o LookupTemplateResultOutput) ViewportLandscape() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.ViewportLandscape }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) ViewportMobile() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.ViewportMobile }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) ViewportTouch() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTemplateResult) bool { return v.ViewportTouch }).(pulumi.BoolOutput)
}

func (o LookupTemplateResultOutput) ViewportWidth() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTemplateResult) int { return v.ViewportWidth }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTemplateResultOutput{})
}
