// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List versions of an existing template, newest first, up to <span pulumi-lang-nodejs="`limit`" pulumi-lang-dotnet="`Limit`" pulumi-lang-go="`limit`" pulumi-lang-python="`limit`" pulumi-lang-yaml="`limit`" pulumi-lang-java="`limit`" pulumi-lang-hcl="`limit`">`limit`</span> (default <span pulumi-lang-nodejs="`1000`" pulumi-lang-dotnet="`1000`" pulumi-lang-go="`1000`" pulumi-lang-python="`1000`" pulumi-lang-yaml="`1000`" pulumi-lang-java="`1000`" pulumi-lang-hcl="`1000`">`1000`</span>). Requires `templates:read`. The provider follows API pagination automatically and preserves exact integer version identifiers.
//
// ## Example Usage
func GetTemplateVersions(ctx *pulumi.Context, args *GetTemplateVersionsArgs, opts ...pulumi.InvokeOption) (*GetTemplateVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTemplateVersionsResult
	err := ctx.Invoke("html-css-to-image:index:getTemplateVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTemplateVersions.
type GetTemplateVersionsArgs struct {
	Id    string `pulumi:"id"`
	Limit *int   `pulumi:"limit"`
}

// A collection of values returned by getTemplateVersions.
type GetTemplateVersionsResult struct {
	Id       string                       `pulumi:"id"`
	Limit    int                          `pulumi:"limit"`
	Versions []GetTemplateVersionsVersion `pulumi:"versions"`
}

func GetTemplateVersionsOutput(ctx *pulumi.Context, args GetTemplateVersionsOutputArgs, opts ...pulumi.InvokeOption) GetTemplateVersionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTemplateVersionsResultOutput, error) {
			args := v.(GetTemplateVersionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("html-css-to-image:index:getTemplateVersions", args, GetTemplateVersionsResultOutput{}, options).(GetTemplateVersionsResultOutput), nil
		}).(GetTemplateVersionsResultOutput)
}

// A collection of arguments for invoking getTemplateVersions.
type GetTemplateVersionsOutputArgs struct {
	Id    pulumi.StringInput `pulumi:"id"`
	Limit pulumi.IntPtrInput `pulumi:"limit"`
}

func (GetTemplateVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplateVersionsArgs)(nil)).Elem()
}

// A collection of values returned by getTemplateVersions.
type GetTemplateVersionsResultOutput struct{ *pulumi.OutputState }

func (GetTemplateVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplateVersionsResult)(nil)).Elem()
}

func (o GetTemplateVersionsResultOutput) ToGetTemplateVersionsResultOutput() GetTemplateVersionsResultOutput {
	return o
}

func (o GetTemplateVersionsResultOutput) ToGetTemplateVersionsResultOutputWithContext(ctx context.Context) GetTemplateVersionsResultOutput {
	return o
}

func (o GetTemplateVersionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTemplateVersionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTemplateVersionsResultOutput) Limit() pulumi.IntOutput {
	return o.ApplyT(func(v GetTemplateVersionsResult) int { return v.Limit }).(pulumi.IntOutput)
}

func (o GetTemplateVersionsResultOutput) Versions() GetTemplateVersionsVersionArrayOutput {
	return o.ApplyT(func(v GetTemplateVersionsResult) []GetTemplateVersionsVersion { return v.Versions }).(GetTemplateVersionsVersionArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTemplateVersionsResultOutput{})
}
