// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ImageUrl struct {
	pulumi.CustomResourceState

	// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
	AdditionalHeaderOrigins pulumi.StringArrayOutput `pulumi:"additionalHeaderOrigins"`
	// Attempt to block cookie/consent banners from displaying.
	BlockConsentBanners pulumi.BoolPtrOutput `pulumi:"blockConsentBanners"`
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrOutput `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// CSS injected into the loaded URL to override styles on the page.
	Css pulumi.StringPtrOutput `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrOutput `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrOutput `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrOutput `pulumi:"format"`
	// Take a screenshot of the entire screen after scrolling down and back to the top.
	FullScreen pulumi.BoolPtrOutput `pulumi:"fullScreen"`
	// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
	Headers pulumi.StringMapOutput `pulumi:"headers"`
	// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
	IdentifyAsHcti pulumi.BoolPtrOutput `pulumi:"identifyAsHcti"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringOutput `pulumi:"imageUrl"`
	// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
	IncludeHeadersOnSubrequests pulumi.BoolPtrOutput `pulumi:"includeHeadersOnSubrequests"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrOutput `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrOutput `pulumi:"jumboMaxWidth"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringOutput `pulumi:"lastRenderStoredAt"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrOutput `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrOutput `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrOutput `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapOutput `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrOutput `pulumi:"msDelay"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringOutput `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringOutput `pulumi:"ogConfigId"`
	// Rendering option.
	PdfOptions ImageUrlPdfOptionsPtrOutput `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrOutput `pulumi:"proxyId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringOutput `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringOutput `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolOutput `pulumi:"renderRequiresAuth"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrOutput `pulumi:"renderWhenReady"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringOutput `pulumi:"savedToStorageDestinationAt"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrOutput `pulumi:"selector"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolOutput `pulumi:"storageDestinationHctiStorageDisabled"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrOutput `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrOutput `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrOutput `pulumi:"transparentBackground"`
	// Public HTTP or HTTPS URL to capture. Required for URL image requests.
	Url pulumi.StringOutput `pulumi:"url"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrOutput `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrOutput `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrOutput `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrOutput `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrOutput `pulumi:"viewportWidth"`
}

// NewImageUrl registers a new resource with the given unique name, arguments, and options.
func NewImageUrl(ctx *pulumi.Context,
	name string, args *ImageUrlArgs, opts ...pulumi.ResourceOption) (*ImageUrl, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	if args.Headers != nil {
		args.Headers = pulumi.ToSecret(args.Headers).(pulumi.StringMapInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"headers",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ImageUrl
	err := ctx.RegisterResource("html-css-to-image:index:ImageUrl", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImageUrl gets an existing ImageUrl resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImageUrl(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageUrlState, opts ...pulumi.ResourceOption) (*ImageUrl, error) {
	var resource ImageUrl
	err := ctx.ReadResource("html-css-to-image:index:ImageUrl", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ImageUrl resources.
type imageUrlState struct {
	// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
	AdditionalHeaderOrigins []string `pulumi:"additionalHeaderOrigins"`
	// Attempt to block cookie/consent banners from displaying.
	BlockConsentBanners *bool `pulumi:"blockConsentBanners"`
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// CSS injected into the loaded URL to override styles on the page.
	Css *string `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Take a screenshot of the entire screen after scrolling down and back to the top.
	FullScreen *bool `pulumi:"fullScreen"`
	// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
	Headers map[string]string `pulumi:"headers"`
	// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
	IdentifyAsHcti *bool `pulumi:"identifyAsHcti"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl *string `pulumi:"imageUrl"`
	// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
	IncludeHeadersOnSubrequests *bool `pulumi:"includeHeadersOnSubrequests"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt *string `pulumi:"lastRenderStoredAt"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce *bool `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata map[string]string `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion *string `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId *string `pulumi:"ogConfigId"`
	// Rendering option.
	PdfOptions *ImageUrlPdfOptions `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl *string `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod *string `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth *bool `pulumi:"renderRequiresAuth"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt *string `pulumi:"savedToStorageDestinationAt"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled *bool `pulumi:"storageDestinationHctiStorageDisabled"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Public HTTP or HTTPS URL to capture. Required for URL image requests.
	Url *string `pulumi:"url"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

type ImageUrlState struct {
	// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
	AdditionalHeaderOrigins pulumi.StringArrayInput
	// Attempt to block cookie/consent banners from displaying.
	BlockConsentBanners pulumi.BoolPtrInput
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// CSS injected into the loaded URL to override styles on the page.
	Css pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Take a screenshot of the entire screen after scrolling down and back to the top.
	FullScreen pulumi.BoolPtrInput
	// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
	Headers pulumi.StringMapInput
	// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
	IdentifyAsHcti pulumi.BoolPtrInput
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringPtrInput
	// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
	IncludeHeadersOnSubrequests pulumi.BoolPtrInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringPtrInput
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringPtrInput
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringPtrInput
	// Rendering option.
	PdfOptions ImageUrlPdfOptionsPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringPtrInput
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringPtrInput
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Public HTTP or HTTPS URL to capture. Required for URL image requests.
	Url pulumi.StringPtrInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (ImageUrlState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageUrlState)(nil)).Elem()
}

type imageUrlArgs struct {
	// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
	AdditionalHeaderOrigins []string `pulumi:"additionalHeaderOrigins"`
	// Attempt to block cookie/consent banners from displaying.
	BlockConsentBanners *bool `pulumi:"blockConsentBanners"`
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// CSS injected into the loaded URL to override styles on the page.
	Css *string `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Take a screenshot of the entire screen after scrolling down and back to the top.
	FullScreen *bool `pulumi:"fullScreen"`
	// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
	Headers map[string]string `pulumi:"headers"`
	// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
	IdentifyAsHcti *bool `pulumi:"identifyAsHcti"`
	// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
	IncludeHeadersOnSubrequests *bool `pulumi:"includeHeadersOnSubrequests"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce *bool `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata map[string]string `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// Rendering option.
	PdfOptions *ImageUrlPdfOptions `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Public HTTP or HTTPS URL to capture. Required for URL image requests.
	Url string `pulumi:"url"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

// The set of arguments for constructing a ImageUrl resource.
type ImageUrlArgs struct {
	// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
	AdditionalHeaderOrigins pulumi.StringArrayInput
	// Attempt to block cookie/consent banners from displaying.
	BlockConsentBanners pulumi.BoolPtrInput
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// CSS injected into the loaded URL to override styles on the page.
	Css pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Take a screenshot of the entire screen after scrolling down and back to the top.
	FullScreen pulumi.BoolPtrInput
	// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
	Headers pulumi.StringMapInput
	// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
	IdentifyAsHcti pulumi.BoolPtrInput
	// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
	IncludeHeadersOnSubrequests pulumi.BoolPtrInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// Rendering option.
	PdfOptions ImageUrlPdfOptionsPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Public HTTP or HTTPS URL to capture. Required for URL image requests.
	Url pulumi.StringInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (ImageUrlArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageUrlArgs)(nil)).Elem()
}

type ImageUrlInput interface {
	pulumi.Input

	ToImageUrlOutput() ImageUrlOutput
	ToImageUrlOutputWithContext(ctx context.Context) ImageUrlOutput
}

func (*ImageUrl) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageUrl)(nil)).Elem()
}

func (i *ImageUrl) ToImageUrlOutput() ImageUrlOutput {
	return i.ToImageUrlOutputWithContext(context.Background())
}

func (i *ImageUrl) ToImageUrlOutputWithContext(ctx context.Context) ImageUrlOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageUrlOutput)
}

type ImageUrlOutput struct{ *pulumi.OutputState }

func (ImageUrlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageUrl)(nil)).Elem()
}

func (o ImageUrlOutput) ToImageUrlOutput() ImageUrlOutput {
	return o
}

func (o ImageUrlOutput) ToImageUrlOutputWithContext(ctx context.Context) ImageUrlOutput {
	return o
}

// Additional exact HTTP or HTTPS origins allowed to receive custom headers. Supports up to 20 unique origins of up to 512 UTF-8 bytes each. Origins must use the format scheme://host[:port] without a path; duplicates are ignored. For GET and form-encoded requests, repeat this parameter for each origin.
func (o ImageUrlOutput) AdditionalHeaderOrigins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringArrayOutput { return v.AdditionalHeaderOrigins }).(pulumi.StringArrayOutput)
}

// Attempt to block cookie/consent banners from displaying.
func (o ImageUrlOutput) BlockConsentBanners() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.BlockConsentBanners }).(pulumi.BoolPtrOutput)
}

// Sets the preferred color scheme: light or dark.
func (o ImageUrlOutput) ColorScheme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.ColorScheme }).(pulumi.StringPtrOutput)
}

// Creation timestamp.
func (o ImageUrlOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// CSS injected into the loaded URL to override styles on the page.
func (o ImageUrlOutput) Css() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.Css }).(pulumi.StringPtrOutput)
}

// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
func (o ImageUrlOutput) DeviceScale() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.Float64PtrOutput { return v.DeviceScale }).(pulumi.Float64PtrOutput)
}

// Disables the Twemoji fallback and renders emoji using native fonts instead.
func (o ImageUrlOutput) DisableTwemoji() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.DisableTwemoji }).(pulumi.BoolPtrOutput)
}

// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
func (o ImageUrlOutput) Format() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.Format }).(pulumi.StringPtrOutput)
}

// Take a screenshot of the entire screen after scrolling down and back to the top.
func (o ImageUrlOutput) FullScreen() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.FullScreen }).(pulumi.BoolPtrOutput)
}

// HTTP headers to include on top-level page navigations to the requested URL's origin and any additional_header_origins. Supports up to 20 headers with names up to 512 ASCII characters and values up to 8192 UTF-8 bytes. For GET and form-encoded requests, repeat this parameter using the format `headers=name:value`.
func (o ImageUrlOutput) Headers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringMapOutput { return v.Headers }).(pulumi.StringMapOutput)
}

// Identify the top-level page navigation as an HCTI screenshot request using the X-HCTI-SCREENSHOT header.
func (o ImageUrlOutput) IdentifyAsHcti() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.IdentifyAsHcti }).(pulumi.BoolPtrOutput)
}

// Rendering operation URL. Creation does not render bytes.
func (o ImageUrlOutput) ImageUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.ImageUrl }).(pulumi.StringOutput)
}

// Include custom headers on subrequests to the requested URL's origin and any additional_header_origins. Defaults to false. Requires at least one header.
func (o ImageUrlOutput) IncludeHeadersOnSubrequests() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.IncludeHeadersOnSubrequests }).(pulumi.BoolPtrOutput)
}

// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o ImageUrlOutput) JumboMaxHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.JumboMaxHeight }).(pulumi.IntPtrOutput)
}

// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o ImageUrlOutput) JumboMaxWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.JumboMaxWidth }).(pulumi.IntPtrOutput)
}

// Last HCTI stored-render timestamp, when available.
func (o ImageUrlOutput) LastRenderStoredAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.LastRenderStoredAt }).(pulumi.StringOutput)
}

// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
func (o ImageUrlOutput) MaxRenderOnce() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.MaxRenderOnce }).(pulumi.BoolPtrOutput)
}

// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
func (o ImageUrlOutput) MaxWaitMs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.MaxWaitMs }).(pulumi.IntPtrOutput)
}

// CSS media type to emulate: screen or print.
func (o ImageUrlOutput) MediaType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.MediaType }).(pulumi.StringPtrOutput)
}

// Custom key-value metadata stored with the image.
func (o ImageUrlOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringMapOutput { return v.Metadata }).(pulumi.StringMapOutput)
}

// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
func (o ImageUrlOutput) MsDelay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.MsDelay }).(pulumi.IntPtrOutput)
}

// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o ImageUrlOutput) OgConfigContentVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.OgConfigContentVersion }).(pulumi.StringOutput)
}

// Associated OG configuration ID, if any.
func (o ImageUrlOutput) OgConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.OgConfigId }).(pulumi.StringOutput)
}

// Rendering option.
func (o ImageUrlOutput) PdfOptions() ImageUrlPdfOptionsPtrOutput {
	return o.ApplyT(func(v *ImageUrl) ImageUrlPdfOptionsPtrOutput { return v.PdfOptions }).(ImageUrlPdfOptionsPtrOutput)
}

// Specifies which configured organization proxy to use when rendering.
func (o ImageUrlOutput) ProxyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.ProxyId }).(pulumi.StringPtrOutput)
}

// Public GET rendering URL, or null when HCTI storage is disabled.
func (o ImageUrlOutput) PublicUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.PublicUrl }).(pulumi.StringOutput)
}

// HTTP method required to render: GET or PUT.
func (o ImageUrlOutput) RenderMethod() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.RenderMethod }).(pulumi.StringOutput)
}

// Whether rendering requires API authentication.
func (o ImageUrlOutput) RenderRequiresAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolOutput { return v.RenderRequiresAuth }).(pulumi.BoolOutput)
}

// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
func (o ImageUrlOutput) RenderWhenReady() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.RenderWhenReady }).(pulumi.BoolPtrOutput)
}

// Last base-image save to custom storage, when available.
func (o ImageUrlOutput) SavedToStorageDestinationAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.SavedToStorageDestinationAt }).(pulumi.StringOutput)
}

// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
func (o ImageUrlOutput) Selector() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.Selector }).(pulumi.StringPtrOutput)
}

// Whether rendered output is saved only to custom storage, recorded when the image was created.
func (o ImageUrlOutput) StorageDestinationHctiStorageDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolOutput { return v.StorageDestinationHctiStorageDisabled }).(pulumi.BoolOutput)
}

// Specifies which configured organization storage destination receives the rendered image.
func (o ImageUrlOutput) StorageDestinationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.StorageDestinationId }).(pulumi.StringPtrOutput)
}

// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
func (o ImageUrlOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringPtrOutput { return v.Timezone }).(pulumi.StringPtrOutput)
}

// Specifies whether the image is rendered with a transparent background.
func (o ImageUrlOutput) TransparentBackground() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.TransparentBackground }).(pulumi.BoolPtrOutput)
}

// Public HTTP or HTTPS URL to capture. Required for URL image requests.
func (o ImageUrlOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o ImageUrlOutput) ViewportHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.ViewportHeight }).(pulumi.IntPtrOutput)
}

// Specifies whether the emulated viewport is in landscape orientation.
func (o ImageUrlOutput) ViewportLandscape() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.ViewportLandscape }).(pulumi.BoolPtrOutput)
}

// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
func (o ImageUrlOutput) ViewportMobile() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.ViewportMobile }).(pulumi.BoolPtrOutput)
}

// Specifies whether the emulated viewport supports touch events.
func (o ImageUrlOutput) ViewportTouch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.BoolPtrOutput { return v.ViewportTouch }).(pulumi.BoolPtrOutput)
}

// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o ImageUrlOutput) ViewportWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageUrl) pulumi.IntPtrOutput { return v.ViewportWidth }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageUrlInput)(nil)).Elem(), &ImageUrl{})
	pulumi.RegisterOutputType(ImageUrlOutput{})
}
