// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ImageHtmlCss struct {
	pulumi.CustomResourceState

	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrOutput `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// CSS used to style the rendered HTML.
	Css pulumi.StringPtrOutput `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrOutput `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrOutput `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrOutput `pulumi:"format"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayOutput `pulumi:"googleFonts"`
	// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
	Html pulumi.StringOutput `pulumi:"html"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringOutput `pulumi:"imageUrl"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrOutput `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrOutput `pulumi:"jumboMaxWidth"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringOutput `pulumi:"lastRenderStoredAt"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrOutput `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrOutput `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrOutput `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapOutput `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrOutput `pulumi:"msDelay"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringOutput `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringOutput `pulumi:"ogConfigId"`
	// Rendering option.
	PdfOptions ImageHtmlCssPdfOptionsPtrOutput `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrOutput `pulumi:"proxyId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringOutput `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringOutput `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolOutput `pulumi:"renderRequiresAuth"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrOutput `pulumi:"renderWhenReady"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringOutput `pulumi:"savedToStorageDestinationAt"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrOutput `pulumi:"selector"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolOutput `pulumi:"storageDestinationHctiStorageDisabled"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrOutput `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrOutput `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrOutput `pulumi:"transparentBackground"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrOutput `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrOutput `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrOutput `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrOutput `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrOutput `pulumi:"viewportWidth"`
}

// NewImageHtmlCss registers a new resource with the given unique name, arguments, and options.
func NewImageHtmlCss(ctx *pulumi.Context,
	name string, args *ImageHtmlCssArgs, opts ...pulumi.ResourceOption) (*ImageHtmlCss, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Html == nil {
		return nil, errors.New("invalid value for required argument 'Html'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ImageHtmlCss
	err := ctx.RegisterResource("html-css-to-image:index:ImageHtmlCss", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImageHtmlCss gets an existing ImageHtmlCss resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImageHtmlCss(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageHtmlCssState, opts ...pulumi.ResourceOption) (*ImageHtmlCss, error) {
	var resource ImageHtmlCss
	err := ctx.ReadResource("html-css-to-image:index:ImageHtmlCss", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ImageHtmlCss resources.
type imageHtmlCssState struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// CSS used to style the rendered HTML.
	Css *string `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts []string `pulumi:"googleFonts"`
	// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
	Html *string `pulumi:"html"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl *string `pulumi:"imageUrl"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt *string `pulumi:"lastRenderStoredAt"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce *bool `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata map[string]string `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion *string `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId *string `pulumi:"ogConfigId"`
	// Rendering option.
	PdfOptions *ImageHtmlCssPdfOptions `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl *string `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod *string `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth *bool `pulumi:"renderRequiresAuth"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt *string `pulumi:"savedToStorageDestinationAt"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled *bool `pulumi:"storageDestinationHctiStorageDisabled"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

type ImageHtmlCssState struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// CSS used to style the rendered HTML.
	Css pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayInput
	// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
	Html pulumi.StringPtrInput
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringPtrInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringPtrInput
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringPtrInput
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringPtrInput
	// Rendering option.
	PdfOptions ImageHtmlCssPdfOptionsPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringPtrInput
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringPtrInput
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (ImageHtmlCssState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageHtmlCssState)(nil)).Elem()
}

type imageHtmlCssArgs struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// CSS used to style the rendered HTML.
	Css *string `pulumi:"css"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts []string `pulumi:"googleFonts"`
	// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
	Html string `pulumi:"html"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce *bool `pulumi:"maxRenderOnce"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Custom key-value metadata stored with the image.
	Metadata map[string]string `pulumi:"metadata"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// Rendering option.
	PdfOptions *ImageHtmlCssPdfOptions `pulumi:"pdfOptions"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

// The set of arguments for constructing a ImageHtmlCss resource.
type ImageHtmlCssArgs struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// CSS used to style the rendered HTML.
	Css pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayInput
	// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
	Html pulumi.StringInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
	MaxRenderOnce pulumi.BoolPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Custom key-value metadata stored with the image.
	Metadata pulumi.StringMapInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// Rendering option.
	PdfOptions ImageHtmlCssPdfOptionsPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (ImageHtmlCssArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageHtmlCssArgs)(nil)).Elem()
}

type ImageHtmlCssInput interface {
	pulumi.Input

	ToImageHtmlCssOutput() ImageHtmlCssOutput
	ToImageHtmlCssOutputWithContext(ctx context.Context) ImageHtmlCssOutput
}

func (*ImageHtmlCss) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageHtmlCss)(nil)).Elem()
}

func (i *ImageHtmlCss) ToImageHtmlCssOutput() ImageHtmlCssOutput {
	return i.ToImageHtmlCssOutputWithContext(context.Background())
}

func (i *ImageHtmlCss) ToImageHtmlCssOutputWithContext(ctx context.Context) ImageHtmlCssOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageHtmlCssOutput)
}

type ImageHtmlCssOutput struct{ *pulumi.OutputState }

func (ImageHtmlCssOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageHtmlCss)(nil)).Elem()
}

func (o ImageHtmlCssOutput) ToImageHtmlCssOutput() ImageHtmlCssOutput {
	return o
}

func (o ImageHtmlCssOutput) ToImageHtmlCssOutputWithContext(ctx context.Context) ImageHtmlCssOutput {
	return o
}

// Sets the preferred color scheme: light or dark.
func (o ImageHtmlCssOutput) ColorScheme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.ColorScheme }).(pulumi.StringPtrOutput)
}

// Creation timestamp.
func (o ImageHtmlCssOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// CSS used to style the rendered HTML.
func (o ImageHtmlCssOutput) Css() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.Css }).(pulumi.StringPtrOutput)
}

// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
func (o ImageHtmlCssOutput) DeviceScale() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.Float64PtrOutput { return v.DeviceScale }).(pulumi.Float64PtrOutput)
}

// Disables the Twemoji fallback and renders emoji using native fonts instead.
func (o ImageHtmlCssOutput) DisableTwemoji() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.DisableTwemoji }).(pulumi.BoolPtrOutput)
}

// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
func (o ImageHtmlCssOutput) Format() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.Format }).(pulumi.StringPtrOutput)
}

// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
func (o ImageHtmlCssOutput) GoogleFonts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringArrayOutput { return v.GoogleFonts }).(pulumi.StringArrayOutput)
}

// HTML to render and take a screenshot of. HTML fragments are rendered in a wrapper document unless a complete HTML document is supplied. Required for HTML image requests.
func (o ImageHtmlCssOutput) Html() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.Html }).(pulumi.StringOutput)
}

// Rendering operation URL. Creation does not render bytes.
func (o ImageHtmlCssOutput) ImageUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.ImageUrl }).(pulumi.StringOutput)
}

// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o ImageHtmlCssOutput) JumboMaxHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.JumboMaxHeight }).(pulumi.IntPtrOutput)
}

// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o ImageHtmlCssOutput) JumboMaxWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.JumboMaxWidth }).(pulumi.IntPtrOutput)
}

// Last HCTI stored-render timestamp, when available.
func (o ImageHtmlCssOutput) LastRenderStoredAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.LastRenderStoredAt }).(pulumi.StringOutput)
}

// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most requests.
func (o ImageHtmlCssOutput) MaxRenderOnce() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.MaxRenderOnce }).(pulumi.BoolPtrOutput)
}

// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
func (o ImageHtmlCssOutput) MaxWaitMs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.MaxWaitMs }).(pulumi.IntPtrOutput)
}

// CSS media type to emulate: screen or print.
func (o ImageHtmlCssOutput) MediaType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.MediaType }).(pulumi.StringPtrOutput)
}

// Custom key-value metadata stored with the image.
func (o ImageHtmlCssOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringMapOutput { return v.Metadata }).(pulumi.StringMapOutput)
}

// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
func (o ImageHtmlCssOutput) MsDelay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.MsDelay }).(pulumi.IntPtrOutput)
}

// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o ImageHtmlCssOutput) OgConfigContentVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.OgConfigContentVersion }).(pulumi.StringOutput)
}

// Associated OG configuration ID, if any.
func (o ImageHtmlCssOutput) OgConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.OgConfigId }).(pulumi.StringOutput)
}

// Rendering option.
func (o ImageHtmlCssOutput) PdfOptions() ImageHtmlCssPdfOptionsPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) ImageHtmlCssPdfOptionsPtrOutput { return v.PdfOptions }).(ImageHtmlCssPdfOptionsPtrOutput)
}

// Specifies which configured organization proxy to use when rendering.
func (o ImageHtmlCssOutput) ProxyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.ProxyId }).(pulumi.StringPtrOutput)
}

// Public GET rendering URL, or null when HCTI storage is disabled.
func (o ImageHtmlCssOutput) PublicUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.PublicUrl }).(pulumi.StringOutput)
}

// HTTP method required to render: GET or PUT.
func (o ImageHtmlCssOutput) RenderMethod() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.RenderMethod }).(pulumi.StringOutput)
}

// Whether rendering requires API authentication.
func (o ImageHtmlCssOutput) RenderRequiresAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolOutput { return v.RenderRequiresAuth }).(pulumi.BoolOutput)
}

// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
func (o ImageHtmlCssOutput) RenderWhenReady() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.RenderWhenReady }).(pulumi.BoolPtrOutput)
}

// Last base-image save to custom storage, when available.
func (o ImageHtmlCssOutput) SavedToStorageDestinationAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringOutput { return v.SavedToStorageDestinationAt }).(pulumi.StringOutput)
}

// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
func (o ImageHtmlCssOutput) Selector() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.Selector }).(pulumi.StringPtrOutput)
}

// Whether rendered output is saved only to custom storage, recorded when the image was created.
func (o ImageHtmlCssOutput) StorageDestinationHctiStorageDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolOutput { return v.StorageDestinationHctiStorageDisabled }).(pulumi.BoolOutput)
}

// Specifies which configured organization storage destination receives the rendered image.
func (o ImageHtmlCssOutput) StorageDestinationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.StorageDestinationId }).(pulumi.StringPtrOutput)
}

// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
func (o ImageHtmlCssOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.StringPtrOutput { return v.Timezone }).(pulumi.StringPtrOutput)
}

// Specifies whether the image is rendered with a transparent background.
func (o ImageHtmlCssOutput) TransparentBackground() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.TransparentBackground }).(pulumi.BoolPtrOutput)
}

// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o ImageHtmlCssOutput) ViewportHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.ViewportHeight }).(pulumi.IntPtrOutput)
}

// Specifies whether the emulated viewport is in landscape orientation.
func (o ImageHtmlCssOutput) ViewportLandscape() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.ViewportLandscape }).(pulumi.BoolPtrOutput)
}

// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
func (o ImageHtmlCssOutput) ViewportMobile() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.ViewportMobile }).(pulumi.BoolPtrOutput)
}

// Specifies whether the emulated viewport supports touch events.
func (o ImageHtmlCssOutput) ViewportTouch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.BoolPtrOutput { return v.ViewportTouch }).(pulumi.BoolPtrOutput)
}

// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o ImageHtmlCssOutput) ViewportWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ImageHtmlCss) pulumi.IntPtrOutput { return v.ViewportWidth }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageHtmlCssInput)(nil)).Elem(), &ImageHtmlCss{})
	pulumi.RegisterOutputType(ImageHtmlCssOutput{})
}
