// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ImageTemplated struct {
	pulumi.CustomResourceState

	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrOutput `pulumi:"format"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringOutput `pulumi:"imageUrl"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringOutput `pulumi:"lastRenderStoredAt"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringOutput `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringOutput `pulumi:"ogConfigId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringOutput `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringOutput `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolOutput `pulumi:"renderRequiresAuth"`
	// Actual template version used at creation; does not pin an omitted template_version. Represented as a decimal string in Pulumi to preserve int64 precision.
	ResolvedTemplateVersion pulumi.StringOutput `pulumi:"resolvedTemplateVersion"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringOutput `pulumi:"savedToStorageDestinationAt"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolOutput `pulumi:"storageDestinationHctiStorageDisabled"`
	// Template ID including the t- prefix.
	TemplateId pulumi.StringOutput `pulumi:"templateId"`
	// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
	TemplateValues pulumi.StringOutput `pulumi:"templateValues"`
	// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrOutput `pulumi:"templateVersion"`
}

// NewImageTemplated registers a new resource with the given unique name, arguments, and options.
func NewImageTemplated(ctx *pulumi.Context,
	name string, args *ImageTemplatedArgs, opts ...pulumi.ResourceOption) (*ImageTemplated, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.TemplateId == nil {
		return nil, errors.New("invalid value for required argument 'TemplateId'")
	}
	if args.TemplateValues == nil {
		return nil, errors.New("invalid value for required argument 'TemplateValues'")
	}
	if args.TemplateValues != nil {
		args.TemplateValues = pulumi.ToSecret(args.TemplateValues).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"templateValues",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ImageTemplated
	err := ctx.RegisterResource("html-css-to-image:index:ImageTemplated", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImageTemplated gets an existing ImageTemplated resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImageTemplated(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageTemplatedState, opts ...pulumi.ResourceOption) (*ImageTemplated, error) {
	var resource ImageTemplated
	err := ctx.ReadResource("html-css-to-image:index:ImageTemplated", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ImageTemplated resources.
type imageTemplatedState struct {
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl *string `pulumi:"imageUrl"`
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt *string `pulumi:"lastRenderStoredAt"`
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion *string `pulumi:"ogConfigContentVersion"`
	// Associated OG configuration ID, if any.
	OgConfigId *string `pulumi:"ogConfigId"`
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl *string `pulumi:"publicUrl"`
	// HTTP method required to render: GET or PUT.
	RenderMethod *string `pulumi:"renderMethod"`
	// Whether rendering requires API authentication.
	RenderRequiresAuth *bool `pulumi:"renderRequiresAuth"`
	// Actual template version used at creation; does not pin an omitted template_version. Represented as a decimal string in Pulumi to preserve int64 precision.
	ResolvedTemplateVersion *string `pulumi:"resolvedTemplateVersion"`
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt *string `pulumi:"savedToStorageDestinationAt"`
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled *bool `pulumi:"storageDestinationHctiStorageDisabled"`
	// Template ID including the t- prefix.
	TemplateId *string `pulumi:"templateId"`
	// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
	TemplateValues *string `pulumi:"templateValues"`
	// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion *string `pulumi:"templateVersion"`
}

type ImageTemplatedState struct {
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Rendering operation URL. Creation does not render bytes.
	ImageUrl pulumi.StringPtrInput
	// Last HCTI stored-render timestamp, when available.
	LastRenderStoredAt pulumi.StringPtrInput
	// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
	OgConfigContentVersion pulumi.StringPtrInput
	// Associated OG configuration ID, if any.
	OgConfigId pulumi.StringPtrInput
	// Public GET rendering URL, or null when HCTI storage is disabled.
	PublicUrl pulumi.StringPtrInput
	// HTTP method required to render: GET or PUT.
	RenderMethod pulumi.StringPtrInput
	// Whether rendering requires API authentication.
	RenderRequiresAuth pulumi.BoolPtrInput
	// Actual template version used at creation; does not pin an omitted template_version. Represented as a decimal string in Pulumi to preserve int64 precision.
	ResolvedTemplateVersion pulumi.StringPtrInput
	// Last base-image save to custom storage, when available.
	SavedToStorageDestinationAt pulumi.StringPtrInput
	// Whether rendered output is saved only to custom storage, recorded when the image was created.
	StorageDestinationHctiStorageDisabled pulumi.BoolPtrInput
	// Template ID including the t- prefix.
	TemplateId pulumi.StringPtrInput
	// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
	TemplateValues pulumi.StringPtrInput
	// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrInput
}

func (ImageTemplatedState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageTemplatedState)(nil)).Elem()
}

type imageTemplatedArgs struct {
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format *string `pulumi:"format"`
	// Template ID including the t- prefix.
	TemplateId string `pulumi:"templateId"`
	// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
	TemplateValues string `pulumi:"templateValues"`
	// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion *string `pulumi:"templateVersion"`
}

// The set of arguments for constructing a ImageTemplated resource.
type ImageTemplatedArgs struct {
	// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
	Format pulumi.StringPtrInput
	// Template ID including the t- prefix.
	TemplateId pulumi.StringInput
	// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
	TemplateValues pulumi.StringInput
	// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrInput
}

func (ImageTemplatedArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageTemplatedArgs)(nil)).Elem()
}

type ImageTemplatedInput interface {
	pulumi.Input

	ToImageTemplatedOutput() ImageTemplatedOutput
	ToImageTemplatedOutputWithContext(ctx context.Context) ImageTemplatedOutput
}

func (*ImageTemplated) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageTemplated)(nil)).Elem()
}

func (i *ImageTemplated) ToImageTemplatedOutput() ImageTemplatedOutput {
	return i.ToImageTemplatedOutputWithContext(context.Background())
}

func (i *ImageTemplated) ToImageTemplatedOutputWithContext(ctx context.Context) ImageTemplatedOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageTemplatedOutput)
}

type ImageTemplatedOutput struct{ *pulumi.OutputState }

func (ImageTemplatedOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageTemplated)(nil)).Elem()
}

func (o ImageTemplatedOutput) ToImageTemplatedOutput() ImageTemplatedOutput {
	return o
}

func (o ImageTemplatedOutput) ToImageTemplatedOutputWithContext(ctx context.Context) ImageTemplatedOutput {
	return o
}

// Creation timestamp.
func (o ImageTemplatedOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Rendering URL format: png, jpg, jpeg, webp, or pdf. Does not restrict later renders to this format.
func (o ImageTemplatedOutput) Format() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringPtrOutput { return v.Format }).(pulumi.StringPtrOutput)
}

// Rendering operation URL. Creation does not render bytes.
func (o ImageTemplatedOutput) ImageUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.ImageUrl }).(pulumi.StringOutput)
}

// Last HCTI stored-render timestamp, when available.
func (o ImageTemplatedOutput) LastRenderStoredAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.LastRenderStoredAt }).(pulumi.StringOutput)
}

// Associated OG content version, if any. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o ImageTemplatedOutput) OgConfigContentVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.OgConfigContentVersion }).(pulumi.StringOutput)
}

// Associated OG configuration ID, if any.
func (o ImageTemplatedOutput) OgConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.OgConfigId }).(pulumi.StringOutput)
}

// Public GET rendering URL, or null when HCTI storage is disabled.
func (o ImageTemplatedOutput) PublicUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.PublicUrl }).(pulumi.StringOutput)
}

// HTTP method required to render: GET or PUT.
func (o ImageTemplatedOutput) RenderMethod() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.RenderMethod }).(pulumi.StringOutput)
}

// Whether rendering requires API authentication.
func (o ImageTemplatedOutput) RenderRequiresAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.BoolOutput { return v.RenderRequiresAuth }).(pulumi.BoolOutput)
}

// Actual template version used at creation; does not pin an omitted template_version. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o ImageTemplatedOutput) ResolvedTemplateVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.ResolvedTemplateVersion }).(pulumi.StringOutput)
}

// Last base-image save to custom storage, when available.
func (o ImageTemplatedOutput) SavedToStorageDestinationAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.SavedToStorageDestinationAt }).(pulumi.StringOutput)
}

// Whether rendered output is saved only to custom storage, recorded when the image was created.
func (o ImageTemplatedOutput) StorageDestinationHctiStorageDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.BoolOutput { return v.StorageDestinationHctiStorageDisabled }).(pulumi.BoolOutput)
}

// Template ID including the t- prefix.
func (o ImageTemplatedOutput) TemplateId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.TemplateId }).(pulumi.StringOutput)
}

// Values substituted into the template for this render. Must be a non-empty JSON object. Include the values needed by the template.
func (o ImageTemplatedOutput) TemplateValues() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringOutput { return v.TemplateValues }).(pulumi.StringOutput)
}

// Optional version to pin. Omission selects the latest version when creating the image. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o ImageTemplatedOutput) TemplateVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ImageTemplated) pulumi.StringPtrOutput { return v.TemplateVersion }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageTemplatedInput)(nil)).Elem(), &ImageTemplated{})
	pulumi.RegisterOutputType(ImageTemplatedOutput{})
}
