// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "html-css-to-image:index:ApiKey":
		r = &ApiKey{}
	case "html-css-to-image:index:ImageHtmlCss":
		r = &ImageHtmlCss{}
	case "html-css-to-image:index:ImageTemplated":
		r = &ImageTemplated{}
	case "html-css-to-image:index:ImageUrl":
		r = &ImageUrl{}
	case "html-css-to-image:index:OgConfig":
		r = &OgConfig{}
	case "html-css-to-image:index:Proxy":
		r = &Proxy{}
	case "html-css-to-image:index:StorageDestination":
		r = &StorageDestination{}
	case "html-css-to-image:index:Template":
		r = &Template{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:html-css-to-image" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"html-css-to-image",
		"index",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"html-css-to-image",
		&pkg{version},
	)
}
