// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type OgConfig struct {
	pulumi.CustomResourceState

	// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
	AdditionalHeaderOrigins pulumi.StringArrayOutput `pulumi:"additionalHeaderOrigins"`
	// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
	BaseUrl pulumi.StringOutput `pulumi:"baseUrl"`
	// Rendering source: html_css or templated. Changing type updates this configuration in place.
	ConfigType pulumi.StringOutput `pulumi:"configType"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
	DefaultOptions OgConfigDefaultOptionsPtrOutput `pulumi:"defaultOptions"`
	// Optional description, up to 1023 characters. Omission clears it.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Disable serving images. Defaults to false.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Serving identifier used in OG image URLs. Distinct from the management ID.
	DomainId pulumi.StringOutput `pulumi:"domainId"`
	// Optimization mode returned by the API.
	EffectiveOptimizationMode pulumi.StringOutput `pulumi:"effectiveOptimizationMode"`
	// Refresh interval returned by the API, in seconds.
	EffectiveRefreshIntervalS pulumi.IntOutput `pulumi:"effectiveRefreshIntervalS"`
	// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
	ExtractValues pulumi.BoolPtrOutput `pulumi:"extractValues"`
	// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
	Headers pulumi.StringMapOutput `pulumi:"headers"`
	// Display name, 1–255 characters after trimming.
	Name pulumi.StringOutput `pulumi:"name"`
	// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
	OptimizationMode pulumi.StringPtrOutput `pulumi:"optimizationMode"`
	// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
	RefreshIntervalS pulumi.IntPtrOutput `pulumi:"refreshIntervalS"`
	// Required for templated configurations. Template ID including its t- prefix.
	TemplateId pulumi.StringPtrOutput `pulumi:"templateId"`
	// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
	TemplateValuesMappings OgConfigTemplateValuesMappingArrayOutput `pulumi:"templateValuesMappings"`
	// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrOutput `pulumi:"templateVersion"`
	// Last update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewOgConfig registers a new resource with the given unique name, arguments, and options.
func NewOgConfig(ctx *pulumi.Context,
	name string, args *OgConfigArgs, opts ...pulumi.ResourceOption) (*OgConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BaseUrl == nil {
		return nil, errors.New("invalid value for required argument 'BaseUrl'")
	}
	if args.ConfigType == nil {
		return nil, errors.New("invalid value for required argument 'ConfigType'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Headers != nil {
		args.Headers = pulumi.ToSecret(args.Headers).(pulumi.StringMapInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"headers",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OgConfig
	err := ctx.RegisterResource("html-css-to-image:index:OgConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOgConfig gets an existing OgConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOgConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OgConfigState, opts ...pulumi.ResourceOption) (*OgConfig, error) {
	var resource OgConfig
	err := ctx.ReadResource("html-css-to-image:index:OgConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OgConfig resources.
type ogConfigState struct {
	// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
	AdditionalHeaderOrigins []string `pulumi:"additionalHeaderOrigins"`
	// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
	BaseUrl *string `pulumi:"baseUrl"`
	// Rendering source: html_css or templated. Changing type updates this configuration in place.
	ConfigType *string `pulumi:"configType"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
	DefaultOptions *OgConfigDefaultOptions `pulumi:"defaultOptions"`
	// Optional description, up to 1023 characters. Omission clears it.
	Description *string `pulumi:"description"`
	// Disable serving images. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Serving identifier used in OG image URLs. Distinct from the management ID.
	DomainId *string `pulumi:"domainId"`
	// Optimization mode returned by the API.
	EffectiveOptimizationMode *string `pulumi:"effectiveOptimizationMode"`
	// Refresh interval returned by the API, in seconds.
	EffectiveRefreshIntervalS *int `pulumi:"effectiveRefreshIntervalS"`
	// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
	ExtractValues *bool `pulumi:"extractValues"`
	// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
	Headers map[string]string `pulumi:"headers"`
	// Display name, 1–255 characters after trimming.
	Name *string `pulumi:"name"`
	// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
	OptimizationMode *string `pulumi:"optimizationMode"`
	// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
	RefreshIntervalS *int `pulumi:"refreshIntervalS"`
	// Required for templated configurations. Template ID including its t- prefix.
	TemplateId *string `pulumi:"templateId"`
	// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
	TemplateValuesMappings []OgConfigTemplateValuesMapping `pulumi:"templateValuesMappings"`
	// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion *string `pulumi:"templateVersion"`
	// Last update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type OgConfigState struct {
	// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
	AdditionalHeaderOrigins pulumi.StringArrayInput
	// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
	BaseUrl pulumi.StringPtrInput
	// Rendering source: html_css or templated. Changing type updates this configuration in place.
	ConfigType pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
	DefaultOptions OgConfigDefaultOptionsPtrInput
	// Optional description, up to 1023 characters. Omission clears it.
	Description pulumi.StringPtrInput
	// Disable serving images. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Serving identifier used in OG image URLs. Distinct from the management ID.
	DomainId pulumi.StringPtrInput
	// Optimization mode returned by the API.
	EffectiveOptimizationMode pulumi.StringPtrInput
	// Refresh interval returned by the API, in seconds.
	EffectiveRefreshIntervalS pulumi.IntPtrInput
	// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
	ExtractValues pulumi.BoolPtrInput
	// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
	Headers pulumi.StringMapInput
	// Display name, 1–255 characters after trimming.
	Name pulumi.StringPtrInput
	// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
	OptimizationMode pulumi.StringPtrInput
	// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
	RefreshIntervalS pulumi.IntPtrInput
	// Required for templated configurations. Template ID including its t- prefix.
	TemplateId pulumi.StringPtrInput
	// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
	TemplateValuesMappings OgConfigTemplateValuesMappingArrayInput
	// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrInput
	// Last update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (OgConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*ogConfigState)(nil)).Elem()
}

type ogConfigArgs struct {
	// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
	AdditionalHeaderOrigins []string `pulumi:"additionalHeaderOrigins"`
	// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
	BaseUrl string `pulumi:"baseUrl"`
	// Rendering source: html_css or templated. Changing type updates this configuration in place.
	ConfigType string `pulumi:"configType"`
	// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
	DefaultOptions *OgConfigDefaultOptions `pulumi:"defaultOptions"`
	// Optional description, up to 1023 characters. Omission clears it.
	Description *string `pulumi:"description"`
	// Disable serving images. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
	ExtractValues *bool `pulumi:"extractValues"`
	// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
	Headers map[string]string `pulumi:"headers"`
	// Display name, 1–255 characters after trimming.
	Name string `pulumi:"name"`
	// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
	OptimizationMode *string `pulumi:"optimizationMode"`
	// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
	RefreshIntervalS *int `pulumi:"refreshIntervalS"`
	// Required for templated configurations. Template ID including its t- prefix.
	TemplateId *string `pulumi:"templateId"`
	// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
	TemplateValuesMappings []OgConfigTemplateValuesMapping `pulumi:"templateValuesMappings"`
	// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion *string `pulumi:"templateVersion"`
}

// The set of arguments for constructing a OgConfig resource.
type OgConfigArgs struct {
	// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
	AdditionalHeaderOrigins pulumi.StringArrayInput
	// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
	BaseUrl pulumi.StringInput
	// Rendering source: html_css or templated. Changing type updates this configuration in place.
	ConfigType pulumi.StringInput
	// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
	DefaultOptions OgConfigDefaultOptionsPtrInput
	// Optional description, up to 1023 characters. Omission clears it.
	Description pulumi.StringPtrInput
	// Disable serving images. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
	ExtractValues pulumi.BoolPtrInput
	// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
	Headers pulumi.StringMapInput
	// Display name, 1–255 characters after trimming.
	Name pulumi.StringInput
	// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
	OptimizationMode pulumi.StringPtrInput
	// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
	RefreshIntervalS pulumi.IntPtrInput
	// Required for templated configurations. Template ID including its t- prefix.
	TemplateId pulumi.StringPtrInput
	// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
	TemplateValuesMappings OgConfigTemplateValuesMappingArrayInput
	// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
	TemplateVersion pulumi.StringPtrInput
}

func (OgConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ogConfigArgs)(nil)).Elem()
}

type OgConfigInput interface {
	pulumi.Input

	ToOgConfigOutput() OgConfigOutput
	ToOgConfigOutputWithContext(ctx context.Context) OgConfigOutput
}

func (*OgConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**OgConfig)(nil)).Elem()
}

func (i *OgConfig) ToOgConfigOutput() OgConfigOutput {
	return i.ToOgConfigOutputWithContext(context.Background())
}

func (i *OgConfig) ToOgConfigOutputWithContext(ctx context.Context) OgConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OgConfigOutput)
}

type OgConfigOutput struct{ *pulumi.OutputState }

func (OgConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OgConfig)(nil)).Elem()
}

func (o OgConfigOutput) ToOgConfigOutput() OgConfigOutput {
	return o
}

func (o OgConfigOutput) ToOgConfigOutputWithContext(ctx context.Context) OgConfigOutput {
	return o
}

// Templated only. Up to 20 additional exact HTTP(S) origins allowed to receive headers, each up to 512 UTF-8 bytes. Omission clears them.
func (o OgConfigOutput) AdditionalHeaderOrigins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringArrayOutput { return v.AdditionalHeaderOrigins }).(pulumi.StringArrayOutput)
}

// HTTPS origin of the source website, up to 2048 characters, without a path, credentials, query, or fragment.
func (o OgConfigOutput) BaseUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.BaseUrl }).(pulumi.StringOutput)
}

// Rendering source: html_css or templated. Changing type updates this configuration in place.
func (o OgConfigOutput) ConfigType() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.ConfigType }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o OgConfigOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// HTML/CSS only. Default page rendering options. Unspecified fields are sent as null; the API owns render defaults.
func (o OgConfigOutput) DefaultOptions() OgConfigDefaultOptionsPtrOutput {
	return o.ApplyT(func(v *OgConfig) OgConfigDefaultOptionsPtrOutput { return v.DefaultOptions }).(OgConfigDefaultOptionsPtrOutput)
}

// Optional description, up to 1023 characters. Omission clears it.
func (o OgConfigOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Disable serving images. Defaults to false.
func (o OgConfigOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Serving identifier used in OG image URLs. Distinct from the management ID.
func (o OgConfigOutput) DomainId() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.DomainId }).(pulumi.StringOutput)
}

// Optimization mode returned by the API.
func (o OgConfigOutput) EffectiveOptimizationMode() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.EffectiveOptimizationMode }).(pulumi.StringOutput)
}

// Refresh interval returned by the API, in seconds.
func (o OgConfigOutput) EffectiveRefreshIntervalS() pulumi.IntOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.IntOutput { return v.EffectiveRefreshIntervalS }).(pulumi.IntOutput)
}

// HTML/CSS only. Extract image options from page metadata, overriding default_options. Omission uses false.
func (o OgConfigOutput) ExtractValues() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.BoolPtrOutput { return v.ExtractValues }).(pulumi.BoolPtrOutput)
}

// Templated only. HTTP extraction headers, up to 20. Names: 512 ASCII characters; values: 8192 UTF-8 bytes. Omission clears them.
func (o OgConfigOutput) Headers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringMapOutput { return v.Headers }).(pulumi.StringMapOutput)
}

// Display name, 1–255 characters after trimming.
func (o OgConfigOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// no_optimization keeps dimensions; post_process adapts after rendering; set_viewport renders at social-platform viewport sizes. Omission lets the API choose its default (currently post_process).
func (o OgConfigOutput) OptimizationMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringPtrOutput { return v.OptimizationMode }).(pulumi.StringPtrOutput)
}

// Seconds before cached images may refresh: 1800–31536000, subject to the plan minimum. Omission lets the API choose its default (currently 86400).
func (o OgConfigOutput) RefreshIntervalS() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.IntPtrOutput { return v.RefreshIntervalS }).(pulumi.IntPtrOutput)
}

// Required for templated configurations. Template ID including its t- prefix.
func (o OgConfigOutput) TemplateId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringPtrOutput { return v.TemplateId }).(pulumi.StringPtrOutput)
}

// Templated only. Up to 32 ordered mappings from page metadata to distinct template fields.
func (o OgConfigOutput) TemplateValuesMappings() OgConfigTemplateValuesMappingArrayOutput {
	return o.ApplyT(func(v *OgConfig) OgConfigTemplateValuesMappingArrayOutput { return v.TemplateValuesMappings }).(OgConfigTemplateValuesMappingArrayOutput)
}

// Templated only. Positive int64 version. Omission follows the latest version at serving time. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o OgConfigOutput) TemplateVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringPtrOutput { return v.TemplateVersion }).(pulumi.StringPtrOutput)
}

// Last update timestamp.
func (o OgConfigOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OgConfig) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OgConfigInput)(nil)).Elem(), &OgConfig{})
	pulumi.RegisterOutputType(OgConfigOutput{})
}
