// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Proxy struct {
	pulumi.CustomResourceState

	// Proxy credentials. Omit the whole object to remove authentication.
	Authentication ProxyAuthenticationPtrOutput `pulumi:"authentication"`
	// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
	BypassHosts pulumi.StringArrayOutput `pulumi:"bypassHosts"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Disable the proxy. Defaults to false.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Port returned by the API.
	EffectivePort pulumi.IntOutput `pulumi:"effectivePort"`
	// Display name, 3–500 characters after trimming.
	Name pulumi.StringOutput `pulumi:"name"`
	// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
	Port pulumi.IntPtrOutput `pulumi:"port"`
	// Last update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
	Url pulumi.StringOutput `pulumi:"url"`
}

// NewProxy registers a new resource with the given unique name, arguments, and options.
func NewProxy(ctx *pulumi.Context,
	name string, args *ProxyArgs, opts ...pulumi.ResourceOption) (*Proxy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Proxy
	err := ctx.RegisterResource("html-css-to-image:index:Proxy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxy gets an existing Proxy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyState, opts ...pulumi.ResourceOption) (*Proxy, error) {
	var resource Proxy
	err := ctx.ReadResource("html-css-to-image:index:Proxy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Proxy resources.
type proxyState struct {
	// Proxy credentials. Omit the whole object to remove authentication.
	Authentication *ProxyAuthentication `pulumi:"authentication"`
	// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
	BypassHosts []string `pulumi:"bypassHosts"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Disable the proxy. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Port returned by the API.
	EffectivePort *int `pulumi:"effectivePort"`
	// Display name, 3–500 characters after trimming.
	Name *string `pulumi:"name"`
	// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
	Port *int `pulumi:"port"`
	// Last update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
	// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
	Url *string `pulumi:"url"`
}

type ProxyState struct {
	// Proxy credentials. Omit the whole object to remove authentication.
	Authentication ProxyAuthenticationPtrInput
	// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
	BypassHosts pulumi.StringArrayInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Disable the proxy. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Port returned by the API.
	EffectivePort pulumi.IntPtrInput
	// Display name, 3–500 characters after trimming.
	Name pulumi.StringPtrInput
	// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
	Port pulumi.IntPtrInput
	// Last update timestamp.
	UpdatedAt pulumi.StringPtrInput
	// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
	Url pulumi.StringPtrInput
}

func (ProxyState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyState)(nil)).Elem()
}

type proxyArgs struct {
	// Proxy credentials. Omit the whole object to remove authentication.
	Authentication *ProxyAuthentication `pulumi:"authentication"`
	// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
	BypassHosts []string `pulumi:"bypassHosts"`
	// Disable the proxy. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Display name, 3–500 characters after trimming.
	Name string `pulumi:"name"`
	// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
	Port *int `pulumi:"port"`
	// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
	Url string `pulumi:"url"`
}

// The set of arguments for constructing a Proxy resource.
type ProxyArgs struct {
	// Proxy credentials. Omit the whole object to remove authentication.
	Authentication ProxyAuthenticationPtrInput
	// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
	BypassHosts pulumi.StringArrayInput
	// Disable the proxy. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Display name, 3–500 characters after trimming.
	Name pulumi.StringInput
	// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
	Port pulumi.IntPtrInput
	// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
	Url pulumi.StringInput
}

func (ProxyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyArgs)(nil)).Elem()
}

type ProxyInput interface {
	pulumi.Input

	ToProxyOutput() ProxyOutput
	ToProxyOutputWithContext(ctx context.Context) ProxyOutput
}

func (*Proxy) ElementType() reflect.Type {
	return reflect.TypeOf((**Proxy)(nil)).Elem()
}

func (i *Proxy) ToProxyOutput() ProxyOutput {
	return i.ToProxyOutputWithContext(context.Background())
}

func (i *Proxy) ToProxyOutputWithContext(ctx context.Context) ProxyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyOutput)
}

type ProxyOutput struct{ *pulumi.OutputState }

func (ProxyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Proxy)(nil)).Elem()
}

func (o ProxyOutput) ToProxyOutput() ProxyOutput {
	return o
}

func (o ProxyOutput) ToProxyOutputWithContext(ctx context.Context) ProxyOutput {
	return o
}

// Proxy credentials. Omit the whole object to remove authentication.
func (o ProxyOutput) Authentication() ProxyAuthenticationPtrOutput {
	return o.ApplyT(func(v *Proxy) ProxyAuthenticationPtrOutput { return v.Authentication }).(ProxyAuthenticationPtrOutput)
}

// Up to 100 hostnames or URLs to bypass. Host comparison ignores case, URL paths, duplicates, and surrounding whitespace. Omission clears the list.
func (o ProxyOutput) BypassHosts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Proxy) pulumi.StringArrayOutput { return v.BypassHosts }).(pulumi.StringArrayOutput)
}

// Creation timestamp.
func (o ProxyOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Proxy) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Disable the proxy. Defaults to false.
func (o ProxyOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Proxy) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Port returned by the API.
func (o ProxyOutput) EffectivePort() pulumi.IntOutput {
	return o.ApplyT(func(v *Proxy) pulumi.IntOutput { return v.EffectivePort }).(pulumi.IntOutput)
}

// Display name, 3–500 characters after trimming.
func (o ProxyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Proxy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Port from 1 to 65535. Omitted sends null; the API chooses the scheme default.
func (o ProxyOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Proxy) pulumi.IntPtrOutput { return v.Port }).(pulumi.IntPtrOutput)
}

// Last update timestamp.
func (o ProxyOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Proxy) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// HTTP(S) proxy origin without credentials, port, query, fragment, or a non-root path.
func (o ProxyOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *Proxy) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyInput)(nil)).Elem(), &Proxy{})
	pulumi.RegisterOutputType(ProxyOutput{})
}
