// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Browser resource type matched by a request override rule.
type RequestOverrideResourceType string

const (
	RequestOverrideResourceTypeBeacon      = RequestOverrideResourceType("beacon")
	RequestOverrideResourceTypeDocument    = RequestOverrideResourceType("document")
	RequestOverrideResourceTypeStylesheet  = RequestOverrideResourceType("stylesheet")
	RequestOverrideResourceTypeImage       = RequestOverrideResourceType("image")
	RequestOverrideResourceTypeImageSet    = RequestOverrideResourceType("image_set")
	RequestOverrideResourceTypeMedia       = RequestOverrideResourceType("media")
	RequestOverrideResourceTypeFont        = RequestOverrideResourceType("font")
	RequestOverrideResourceTypeScript      = RequestOverrideResourceType("script")
	RequestOverrideResourceTypeTextTrack   = RequestOverrideResourceType("text_track")
	RequestOverrideResourceTypeXhr         = RequestOverrideResourceType("xhr")
	RequestOverrideResourceTypeFetch       = RequestOverrideResourceType("fetch")
	RequestOverrideResourceTypeEventSource = RequestOverrideResourceType("event_source")
	RequestOverrideResourceTypeManifest    = RequestOverrideResourceType("manifest")
	RequestOverrideResourceTypePing        = RequestOverrideResourceType("ping")
	RequestOverrideResourceTypeImg         = RequestOverrideResourceType("img")
	RequestOverrideResourceTypeOther       = RequestOverrideResourceType("other")
)

func (RequestOverrideResourceType) ElementType() reflect.Type {
	return reflect.TypeOf((*RequestOverrideResourceType)(nil)).Elem()
}

func (e RequestOverrideResourceType) ToRequestOverrideResourceTypeOutput() RequestOverrideResourceTypeOutput {
	return pulumi.ToOutput(e).(RequestOverrideResourceTypeOutput)
}

func (e RequestOverrideResourceType) ToRequestOverrideResourceTypeOutputWithContext(ctx context.Context) RequestOverrideResourceTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RequestOverrideResourceTypeOutput)
}

func (e RequestOverrideResourceType) ToRequestOverrideResourceTypePtrOutput() RequestOverrideResourceTypePtrOutput {
	return e.ToRequestOverrideResourceTypePtrOutputWithContext(context.Background())
}

func (e RequestOverrideResourceType) ToRequestOverrideResourceTypePtrOutputWithContext(ctx context.Context) RequestOverrideResourceTypePtrOutput {
	return RequestOverrideResourceType(e).ToRequestOverrideResourceTypeOutputWithContext(ctx).ToRequestOverrideResourceTypePtrOutputWithContext(ctx)
}

func (e RequestOverrideResourceType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e RequestOverrideResourceType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e RequestOverrideResourceType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e RequestOverrideResourceType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RequestOverrideResourceTypeOutput struct{ *pulumi.OutputState }

func (RequestOverrideResourceTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RequestOverrideResourceType)(nil)).Elem()
}

func (o RequestOverrideResourceTypeOutput) ToRequestOverrideResourceTypeOutput() RequestOverrideResourceTypeOutput {
	return o
}

func (o RequestOverrideResourceTypeOutput) ToRequestOverrideResourceTypeOutputWithContext(ctx context.Context) RequestOverrideResourceTypeOutput {
	return o
}

func (o RequestOverrideResourceTypeOutput) ToRequestOverrideResourceTypePtrOutput() RequestOverrideResourceTypePtrOutput {
	return o.ToRequestOverrideResourceTypePtrOutputWithContext(context.Background())
}

func (o RequestOverrideResourceTypeOutput) ToRequestOverrideResourceTypePtrOutputWithContext(ctx context.Context) RequestOverrideResourceTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RequestOverrideResourceType) *RequestOverrideResourceType {
		return &v
	}).(RequestOverrideResourceTypePtrOutput)
}

func (o RequestOverrideResourceTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RequestOverrideResourceTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RequestOverrideResourceType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RequestOverrideResourceTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RequestOverrideResourceTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RequestOverrideResourceType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RequestOverrideResourceTypePtrOutput struct{ *pulumi.OutputState }

func (RequestOverrideResourceTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RequestOverrideResourceType)(nil)).Elem()
}

func (o RequestOverrideResourceTypePtrOutput) ToRequestOverrideResourceTypePtrOutput() RequestOverrideResourceTypePtrOutput {
	return o
}

func (o RequestOverrideResourceTypePtrOutput) ToRequestOverrideResourceTypePtrOutputWithContext(ctx context.Context) RequestOverrideResourceTypePtrOutput {
	return o
}

func (o RequestOverrideResourceTypePtrOutput) Elem() RequestOverrideResourceTypeOutput {
	return o.ApplyT(func(v *RequestOverrideResourceType) RequestOverrideResourceType {
		if v != nil {
			return *v
		}
		var ret RequestOverrideResourceType
		return ret
	}).(RequestOverrideResourceTypeOutput)
}

func (o RequestOverrideResourceTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RequestOverrideResourceTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RequestOverrideResourceType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RequestOverrideResourceTypeInput is an input type that accepts values of the RequestOverrideResourceType enum
// A concrete instance of `RequestOverrideResourceTypeInput` can be one of the following:
//
//	RequestOverrideResourceTypeBeacon
//	RequestOverrideResourceTypeDocument
//	RequestOverrideResourceTypeStylesheet
//	RequestOverrideResourceTypeImage
//	RequestOverrideResourceTypeImageSet
//	RequestOverrideResourceTypeMedia
//	RequestOverrideResourceTypeFont
//	RequestOverrideResourceTypeScript
//	RequestOverrideResourceTypeTextTrack
//	RequestOverrideResourceTypeXhr
//	RequestOverrideResourceTypeFetch
//	RequestOverrideResourceTypeEventSource
//	RequestOverrideResourceTypeManifest
//	RequestOverrideResourceTypePing
//	RequestOverrideResourceTypeImg
//	RequestOverrideResourceTypeOther
type RequestOverrideResourceTypeInput interface {
	pulumi.Input

	ToRequestOverrideResourceTypeOutput() RequestOverrideResourceTypeOutput
	ToRequestOverrideResourceTypeOutputWithContext(context.Context) RequestOverrideResourceTypeOutput
}

var requestOverrideResourceTypePtrType = reflect.TypeOf((**RequestOverrideResourceType)(nil)).Elem()

type RequestOverrideResourceTypePtrInput interface {
	pulumi.Input

	ToRequestOverrideResourceTypePtrOutput() RequestOverrideResourceTypePtrOutput
	ToRequestOverrideResourceTypePtrOutputWithContext(context.Context) RequestOverrideResourceTypePtrOutput
}

type requestOverrideResourceTypePtr string

func RequestOverrideResourceTypePtr(v string) RequestOverrideResourceTypePtrInput {
	return (*requestOverrideResourceTypePtr)(&v)
}

func (*requestOverrideResourceTypePtr) ElementType() reflect.Type {
	return requestOverrideResourceTypePtrType
}

func (in *requestOverrideResourceTypePtr) ToRequestOverrideResourceTypePtrOutput() RequestOverrideResourceTypePtrOutput {
	return pulumi.ToOutput(in).(RequestOverrideResourceTypePtrOutput)
}

func (in *requestOverrideResourceTypePtr) ToRequestOverrideResourceTypePtrOutputWithContext(ctx context.Context) RequestOverrideResourceTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RequestOverrideResourceTypePtrOutput)
}

// RequestOverrideResourceTypeArrayInput is an input type that accepts RequestOverrideResourceTypeArray and RequestOverrideResourceTypeArrayOutput values.
// You can construct a concrete instance of `RequestOverrideResourceTypeArrayInput` via:
//
//	RequestOverrideResourceTypeArray{ RequestOverrideResourceTypeArgs{...} }
type RequestOverrideResourceTypeArrayInput interface {
	pulumi.Input

	ToRequestOverrideResourceTypeArrayOutput() RequestOverrideResourceTypeArrayOutput
	ToRequestOverrideResourceTypeArrayOutputWithContext(context.Context) RequestOverrideResourceTypeArrayOutput
}

type RequestOverrideResourceTypeArray []RequestOverrideResourceType

func (RequestOverrideResourceTypeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RequestOverrideResourceType)(nil)).Elem()
}

func (i RequestOverrideResourceTypeArray) ToRequestOverrideResourceTypeArrayOutput() RequestOverrideResourceTypeArrayOutput {
	return i.ToRequestOverrideResourceTypeArrayOutputWithContext(context.Background())
}

func (i RequestOverrideResourceTypeArray) ToRequestOverrideResourceTypeArrayOutputWithContext(ctx context.Context) RequestOverrideResourceTypeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RequestOverrideResourceTypeArrayOutput)
}

type RequestOverrideResourceTypeArrayOutput struct{ *pulumi.OutputState }

func (RequestOverrideResourceTypeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RequestOverrideResourceType)(nil)).Elem()
}

func (o RequestOverrideResourceTypeArrayOutput) ToRequestOverrideResourceTypeArrayOutput() RequestOverrideResourceTypeArrayOutput {
	return o
}

func (o RequestOverrideResourceTypeArrayOutput) ToRequestOverrideResourceTypeArrayOutputWithContext(ctx context.Context) RequestOverrideResourceTypeArrayOutput {
	return o
}

func (o RequestOverrideResourceTypeArrayOutput) Index(i pulumi.IntInput) RequestOverrideResourceTypeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RequestOverrideResourceType {
		return vs[0].([]RequestOverrideResourceType)[vs[1].(int)]
	}).(RequestOverrideResourceTypeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RequestOverrideResourceTypeInput)(nil)).Elem(), RequestOverrideResourceType("beacon"))
	pulumi.RegisterInputType(reflect.TypeOf((*RequestOverrideResourceTypePtrInput)(nil)).Elem(), RequestOverrideResourceType("beacon"))
	pulumi.RegisterInputType(reflect.TypeOf((*RequestOverrideResourceTypeArrayInput)(nil)).Elem(), RequestOverrideResourceTypeArray{})
	pulumi.RegisterOutputType(RequestOverrideResourceTypeOutput{})
	pulumi.RegisterOutputType(RequestOverrideResourceTypePtrOutput{})
	pulumi.RegisterOutputType(RequestOverrideResourceTypeArrayOutput{})
}
