// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StorageDestination struct {
	pulumi.CustomResourceState

	// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
	ConnectionInfo StorageDestinationConnectionInfoOutput `pulumi:"connectionInfo"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Disable this destination for new renders. Defaults to false.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
	HctiStorageDisabled pulumi.BoolOutput `pulumi:"hctiStorageDisabled"`
	// Latest API connection test error, or null. Marked sensitive because it is external service diagnostic text.
	LastTestError pulumi.StringOutput `pulumi:"lastTestError"`
	// Latest API connection test result, or null.
	LastTestSucceeded pulumi.BoolOutput `pulumi:"lastTestSucceeded"`
	// Timestamp of the latest API connection test, or null. Refresh does not run tests.
	LastTestedAt pulumi.StringOutput `pulumi:"lastTestedAt"`
	// Display name, 3–255 characters after trimming.
	Name pulumi.StringOutput `pulumi:"name"`
	// Last update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewStorageDestination registers a new resource with the given unique name, arguments, and options.
func NewStorageDestination(ctx *pulumi.Context,
	name string, args *StorageDestinationArgs, opts ...pulumi.ResourceOption) (*StorageDestination, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectionInfo == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionInfo'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"lastTestError",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource StorageDestination
	err := ctx.RegisterResource("html-css-to-image:index:StorageDestination", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStorageDestination gets an existing StorageDestination resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStorageDestination(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StorageDestinationState, opts ...pulumi.ResourceOption) (*StorageDestination, error) {
	var resource StorageDestination
	err := ctx.ReadResource("html-css-to-image:index:StorageDestination", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StorageDestination resources.
type storageDestinationState struct {
	// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
	ConnectionInfo *StorageDestinationConnectionInfo `pulumi:"connectionInfo"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Disable this destination for new renders. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
	HctiStorageDisabled *bool `pulumi:"hctiStorageDisabled"`
	// Latest API connection test error, or null. Marked sensitive because it is external service diagnostic text.
	LastTestError *string `pulumi:"lastTestError"`
	// Latest API connection test result, or null.
	LastTestSucceeded *bool `pulumi:"lastTestSucceeded"`
	// Timestamp of the latest API connection test, or null. Refresh does not run tests.
	LastTestedAt *string `pulumi:"lastTestedAt"`
	// Display name, 3–255 characters after trimming.
	Name *string `pulumi:"name"`
	// Last update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type StorageDestinationState struct {
	// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
	ConnectionInfo StorageDestinationConnectionInfoPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Disable this destination for new renders. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
	HctiStorageDisabled pulumi.BoolPtrInput
	// Latest API connection test error, or null. Marked sensitive because it is external service diagnostic text.
	LastTestError pulumi.StringPtrInput
	// Latest API connection test result, or null.
	LastTestSucceeded pulumi.BoolPtrInput
	// Timestamp of the latest API connection test, or null. Refresh does not run tests.
	LastTestedAt pulumi.StringPtrInput
	// Display name, 3–255 characters after trimming.
	Name pulumi.StringPtrInput
	// Last update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (StorageDestinationState) ElementType() reflect.Type {
	return reflect.TypeOf((*storageDestinationState)(nil)).Elem()
}

type storageDestinationArgs struct {
	// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
	ConnectionInfo StorageDestinationConnectionInfo `pulumi:"connectionInfo"`
	// Disable this destination for new renders. Defaults to false.
	Disabled *bool `pulumi:"disabled"`
	// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
	HctiStorageDisabled *bool `pulumi:"hctiStorageDisabled"`
	// Display name, 3–255 characters after trimming.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a StorageDestination resource.
type StorageDestinationArgs struct {
	// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
	ConnectionInfo StorageDestinationConnectionInfoInput
	// Disable this destination for new renders. Defaults to false.
	Disabled pulumi.BoolPtrInput
	// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
	HctiStorageDisabled pulumi.BoolPtrInput
	// Display name, 3–255 characters after trimming.
	Name pulumi.StringInput
}

func (StorageDestinationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storageDestinationArgs)(nil)).Elem()
}

type StorageDestinationInput interface {
	pulumi.Input

	ToStorageDestinationOutput() StorageDestinationOutput
	ToStorageDestinationOutputWithContext(ctx context.Context) StorageDestinationOutput
}

func (*StorageDestination) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageDestination)(nil)).Elem()
}

func (i *StorageDestination) ToStorageDestinationOutput() StorageDestinationOutput {
	return i.ToStorageDestinationOutputWithContext(context.Background())
}

func (i *StorageDestination) ToStorageDestinationOutputWithContext(ctx context.Context) StorageDestinationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StorageDestinationOutput)
}

type StorageDestinationOutput struct{ *pulumi.OutputState }

func (StorageDestinationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageDestination)(nil)).Elem()
}

func (o StorageDestinationOutput) ToStorageDestinationOutput() StorageDestinationOutput {
	return o
}

func (o StorageDestinationOutput) ToStorageDestinationOutputWithContext(ctx context.Context) StorageDestinationOutput {
	return o
}

// Set exactly one provider object: aws_s3, cloudflare_r2, backblaze_b2, digitalocean_spaces, wasabi, google_cloud_storage, or other_s3_compatible. Switching objects updates in place.
func (o StorageDestinationOutput) ConnectionInfo() StorageDestinationConnectionInfoOutput {
	return o.ApplyT(func(v *StorageDestination) StorageDestinationConnectionInfoOutput { return v.ConnectionInfo }).(StorageDestinationConnectionInfoOutput)
}

// Creation timestamp.
func (o StorageDestinationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Disable this destination for new renders. Defaults to false.
func (o StorageDestinationOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Store output only at this destination. Defaults to false. True requires authenticated /store rendering and supplies no public HCTI CDN URL.
func (o StorageDestinationOutput) HctiStorageDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.BoolOutput { return v.HctiStorageDisabled }).(pulumi.BoolOutput)
}

// Latest API connection test error, or null. Marked sensitive because it is external service diagnostic text.
func (o StorageDestinationOutput) LastTestError() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.StringOutput { return v.LastTestError }).(pulumi.StringOutput)
}

// Latest API connection test result, or null.
func (o StorageDestinationOutput) LastTestSucceeded() pulumi.BoolOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.BoolOutput { return v.LastTestSucceeded }).(pulumi.BoolOutput)
}

// Timestamp of the latest API connection test, or null. Refresh does not run tests.
func (o StorageDestinationOutput) LastTestedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.StringOutput { return v.LastTestedAt }).(pulumi.StringOutput)
}

// Display name, 3–255 characters after trimming.
func (o StorageDestinationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Last update timestamp.
func (o StorageDestinationOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageDestination) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StorageDestinationInput)(nil)).Elem(), &StorageDestination{})
	pulumi.RegisterOutputType(StorageDestinationOutput{})
}
