// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package htmlcsstoimage

import (
	"context"
	"reflect"

	"errors"
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Template struct {
	pulumi.CustomResourceState

	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrOutput `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
	Css pulumi.StringPtrOutput `pulumi:"css"`
	// An optional description of the template for your reference. Maximum: 1024 characters.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrOutput `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrOutput `pulumi:"disableTwemoji"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayOutput `pulumi:"googleFonts"`
	// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
	Html pulumi.StringOutput `pulumi:"html"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrOutput `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrOutput `pulumi:"jumboMaxWidth"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrOutput `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrOutput `pulumi:"mediaType"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrOutput `pulumi:"msDelay"`
	// The name of the template, used to identify it in your account. Maximum: 64 characters.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrOutput `pulumi:"proxyId"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrOutput `pulumi:"renderWhenReady"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrOutput `pulumi:"selector"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrOutput `pulumi:"storageDestinationId"`
	// Template type; this resource manages html_css templates.
	TemplateType pulumi.StringOutput `pulumi:"templateType"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrOutput `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrOutput `pulumi:"transparentBackground"`
	// Last update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Latest saved template version. Represented as a decimal string in Pulumi to preserve int64 precision.
	Version pulumi.StringOutput `pulumi:"version"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrOutput `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrOutput `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrOutput `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrOutput `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrOutput `pulumi:"viewportWidth"`
}

// NewTemplate registers a new resource with the given unique name, arguments, and options.
func NewTemplate(ctx *pulumi.Context,
	name string, args *TemplateArgs, opts ...pulumi.ResourceOption) (*Template, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Html == nil {
		return nil, errors.New("invalid value for required argument 'Html'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Template
	err := ctx.RegisterResource("html-css-to-image:index:Template", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTemplate gets an existing Template resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTemplate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TemplateState, opts ...pulumi.ResourceOption) (*Template, error) {
	var resource Template
	err := ctx.ReadResource("html-css-to-image:index:Template", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Template resources.
type templateState struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
	Css *string `pulumi:"css"`
	// An optional description of the template for your reference. Maximum: 1024 characters.
	Description *string `pulumi:"description"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts []string `pulumi:"googleFonts"`
	// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
	Html *string `pulumi:"html"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// The name of the template, used to identify it in your account. Maximum: 64 characters.
	Name *string `pulumi:"name"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Template type; this resource manages html_css templates.
	TemplateType *string `pulumi:"templateType"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Last update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Latest saved template version. Represented as a decimal string in Pulumi to preserve int64 precision.
	Version *string `pulumi:"version"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

type TemplateState struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
	Css pulumi.StringPtrInput
	// An optional description of the template for your reference. Maximum: 1024 characters.
	Description pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayInput
	// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
	Html pulumi.StringPtrInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// The name of the template, used to identify it in your account. Maximum: 64 characters.
	Name pulumi.StringPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Template type; this resource manages html_css templates.
	TemplateType pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Last update timestamp.
	UpdatedAt pulumi.StringPtrInput
	// Latest saved template version. Represented as a decimal string in Pulumi to preserve int64 precision.
	Version pulumi.StringPtrInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (TemplateState) ElementType() reflect.Type {
	return reflect.TypeOf((*templateState)(nil)).Elem()
}

type templateArgs struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme *string `pulumi:"colorScheme"`
	// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
	Css *string `pulumi:"css"`
	// An optional description of the template for your reference. Maximum: 1024 characters.
	Description *string `pulumi:"description"`
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale *float64 `pulumi:"deviceScale"`
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji *bool `pulumi:"disableTwemoji"`
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts []string `pulumi:"googleFonts"`
	// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
	Html string `pulumi:"html"`
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight *int `pulumi:"jumboMaxHeight"`
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth *int `pulumi:"jumboMaxWidth"`
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs *int `pulumi:"maxWaitMs"`
	// CSS media type to emulate: screen or print.
	MediaType *string `pulumi:"mediaType"`
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay *int `pulumi:"msDelay"`
	// The name of the template, used to identify it in your account. Maximum: 64 characters.
	Name *string `pulumi:"name"`
	// Specifies which configured organization proxy to use when rendering.
	ProxyId *string `pulumi:"proxyId"`
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady *bool `pulumi:"renderWhenReady"`
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector *string `pulumi:"selector"`
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId *string `pulumi:"storageDestinationId"`
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone *string `pulumi:"timezone"`
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground *bool `pulumi:"transparentBackground"`
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight *int `pulumi:"viewportHeight"`
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape *bool `pulumi:"viewportLandscape"`
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile *bool `pulumi:"viewportMobile"`
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch *bool `pulumi:"viewportTouch"`
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth *int `pulumi:"viewportWidth"`
}

// The set of arguments for constructing a Template resource.
type TemplateArgs struct {
	// Sets the preferred color scheme: light or dark.
	ColorScheme pulumi.StringPtrInput
	// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
	Css pulumi.StringPtrInput
	// An optional description of the template for your reference. Maximum: 1024 characters.
	Description pulumi.StringPtrInput
	// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
	DeviceScale pulumi.Float64PtrInput
	// Disables the Twemoji fallback and renders emoji using native fonts instead.
	DisableTwemoji pulumi.BoolPtrInput
	// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
	GoogleFonts pulumi.StringArrayInput
	// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
	Html pulumi.StringInput
	// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxHeight pulumi.IntPtrInput
	// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
	JumboMaxWidth pulumi.IntPtrInput
	// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
	MaxWaitMs pulumi.IntPtrInput
	// CSS media type to emulate: screen or print.
	MediaType pulumi.StringPtrInput
	// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
	MsDelay pulumi.IntPtrInput
	// The name of the template, used to identify it in your account. Maximum: 64 characters.
	Name pulumi.StringPtrInput
	// Specifies which configured organization proxy to use when rendering.
	ProxyId pulumi.StringPtrInput
	// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
	RenderWhenReady pulumi.BoolPtrInput
	// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
	Selector pulumi.StringPtrInput
	// Specifies which configured organization storage destination receives the rendered image.
	StorageDestinationId pulumi.StringPtrInput
	// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
	Timezone pulumi.StringPtrInput
	// Specifies whether the image is rendered with a transparent background.
	TransparentBackground pulumi.BoolPtrInput
	// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportHeight pulumi.IntPtrInput
	// Specifies whether the emulated viewport is in landscape orientation.
	ViewportLandscape pulumi.BoolPtrInput
	// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
	ViewportMobile pulumi.BoolPtrInput
	// Specifies whether the emulated viewport supports touch events.
	ViewportTouch pulumi.BoolPtrInput
	// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
	ViewportWidth pulumi.IntPtrInput
}

func (TemplateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*templateArgs)(nil)).Elem()
}

type TemplateInput interface {
	pulumi.Input

	ToTemplateOutput() TemplateOutput
	ToTemplateOutputWithContext(ctx context.Context) TemplateOutput
}

func (*Template) ElementType() reflect.Type {
	return reflect.TypeOf((**Template)(nil)).Elem()
}

func (i *Template) ToTemplateOutput() TemplateOutput {
	return i.ToTemplateOutputWithContext(context.Background())
}

func (i *Template) ToTemplateOutputWithContext(ctx context.Context) TemplateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateOutput)
}

type TemplateOutput struct{ *pulumi.OutputState }

func (TemplateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Template)(nil)).Elem()
}

func (o TemplateOutput) ToTemplateOutput() TemplateOutput {
	return o
}

func (o TemplateOutput) ToTemplateOutputWithContext(ctx context.Context) TemplateOutput {
	return o
}

// Sets the preferred color scheme: light or dark.
func (o TemplateOutput) ColorScheme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.ColorScheme }).(pulumi.StringPtrOutput)
}

// Creation timestamp.
func (o TemplateOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// CSS used to style images rendered from the template. Handlebars expressions are not supported in CSS; put dynamic CSS in the HTML instead.
func (o TemplateOutput) Css() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Css }).(pulumi.StringPtrOutput)
}

// An optional description of the template for your reference. Maximum: 1024 characters.
func (o TemplateOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Adjusts the pixel ratio used for the screenshot. Minimum: 0.1. Maximum: 3. HTML and template renders default to 2; URL renders default to 1.
func (o TemplateOutput) DeviceScale() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Template) pulumi.Float64PtrOutput { return v.DeviceScale }).(pulumi.Float64PtrOutput)
}

// Disables the Twemoji fallback and renders emoji using native fonts instead.
func (o TemplateOutput) DisableTwemoji() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.DisableTwemoji }).(pulumi.BoolPtrOutput)
}

// Google fonts to load. Separate multiple fonts with a pipe, such as 'Roboto|OpenSans', and set font-family in the CSS to use them.
func (o TemplateOutput) GoogleFonts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Template) pulumi.StringArrayOutput { return v.GoogleFonts }).(pulumi.StringArrayOutput)
}

// HTML to render for the template. Use Handlebars placeholders for values that will be substituted when an image is rendered. Must be non-empty, contain at least one Handlebars placeholder, and compile as valid Handlebars.
func (o TemplateOutput) Html() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.Html }).(pulumi.StringOutput)
}

// Maximum height of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_width. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o TemplateOutput) JumboMaxHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.JumboMaxHeight }).(pulumi.IntPtrOutput)
}

// Maximum width of the rendered image in jumbo mode. Jumbo rendering consumes additional renders and requires jumbo_max_height. Supply both jumbo dimensions. Each must be greater than 0 and no more than 80000; at least one must exceed 8000; total area cannot exceed 400000000 pixels.
func (o TemplateOutput) JumboMaxWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.JumboMaxWidth }).(pulumi.IntPtrOutput)
}

// Sets a limit on how long to wait before taking the screenshot when the page continues loading irrelevant content. Minimum: 500. Maximum: 10000 and subject to the account plan limit.
func (o TemplateOutput) MaxWaitMs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.MaxWaitMs }).(pulumi.IntPtrOutput)
}

// CSS media type to emulate: screen or print.
func (o TemplateOutput) MediaType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.MediaType }).(pulumi.StringPtrOutput)
}

// Adds extra time in milliseconds before taking the screenshot so JavaScript can execute. Minimum: 0. Maximum: 10000.
func (o TemplateOutput) MsDelay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.MsDelay }).(pulumi.IntPtrOutput)
}

// The name of the template, used to identify it in your account. Maximum: 64 characters.
func (o TemplateOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Specifies which configured organization proxy to use when rendering.
func (o TemplateOutput) ProxyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.ProxyId }).(pulumi.StringPtrOutput)
}

// Waits until the page signals that the screenshot is ready. The image fails if the readiness signal is never sent.
func (o TemplateOutput) RenderWhenReady() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.RenderWhenReady }).(pulumi.BoolPtrOutput)
}

// A CSS selector for an element in the HTML. We’ll crop the image to this specific element.
func (o TemplateOutput) Selector() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Selector }).(pulumi.StringPtrOutput)
}

// Specifies which configured organization storage destination receives the rendered image.
func (o TemplateOutput) StorageDestinationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.StorageDestinationId }).(pulumi.StringPtrOutput)
}

// Template type; this resource manages html_css templates.
func (o TemplateOutput) TemplateType() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.TemplateType }).(pulumi.StringOutput)
}

// Sets the IANA timezone used by Chrome while rendering. Must be a recognized IANA timezone identifier.
func (o TemplateOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Timezone }).(pulumi.StringPtrOutput)
}

// Specifies whether the image is rendered with a transparent background.
func (o TemplateOutput) TransparentBackground() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.TransparentBackground }).(pulumi.BoolPtrOutput)
}

// Last update timestamp.
func (o TemplateOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Latest saved template version. Represented as a decimal string in Pulumi to preserve int64 precision.
func (o TemplateOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

// Sets the height of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o TemplateOutput) ViewportHeight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.ViewportHeight }).(pulumi.IntPtrOutput)
}

// Specifies whether the emulated viewport is in landscape orientation.
func (o TemplateOutput) ViewportLandscape() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.ViewportLandscape }).(pulumi.BoolPtrOutput)
}

// Specifies whether the page uses mobile viewport behavior, including its viewport meta tag.
func (o TemplateOutput) ViewportMobile() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.ViewportMobile }).(pulumi.BoolPtrOutput)
}

// Specifies whether the emulated viewport supports touch events.
func (o TemplateOutput) ViewportTouch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolPtrOutput { return v.ViewportTouch }).(pulumi.BoolPtrOutput)
}

// Sets the width of Chrome's viewport and disables automatic cropping. Minimum: 1. Maximum: 6000. Both viewport dimensions must be supplied together.
func (o TemplateOutput) ViewportWidth() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.ViewportWidth }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateInput)(nil)).Elem(), &Template{})
	pulumi.RegisterOutputType(TemplateOutput{})
}
