// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/htmlcsstoimage/pulumi-html-css-to-image/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// API ID. Falls back to HCTI_API_ID.
func GetApiId(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "html-css-to-image:apiId")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "HCTI_API_ID"); d != nil {
		value = d.(string)
	}
	return value
}

// API key. Falls back to HCTI_API_KEY.
func GetApiKey(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "html-css-to-image:apiKey")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "HCTI_API_KEY"); d != nil {
		value = d.(string)
	}
	return value
}

// API origin. Defaults to https://hcti.io.
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "html-css-to-image:baseUrl")
}
